const { rethinkdb } = require('../../../settings.js');

module.exports.ClientOptions = {
	disabledEvents: [
		'GUILD_SYNC',
		'CHANNEL_PINS_UPDATE',
		'MESSAGE_REACTION_ADD',
		'MESSAGE_REACTION_REMOVE',
		'MESSAGE_REACTION_REMOVE_ALL',
		'USER_NOTE_UPDATE',
		'USER_SETTINGS_UPDATE',
		'TYPING_START',
		'VOICE_SERVER_UPDATE',
		'RELATIONSHIP_ADD',
		'RELATIONSHIP_REMOVE'
	],
	disableEveryone: true,
	messageCacheMaxSize: 100,
	messageCacheLifetime: 240,
	messageSweepInterval: 300,
	commandEditing: true,
	commandLogging: true,
	gateways: { clientStorage: { provider: 'json' } },
	providers: {
		default: 'rethinkdb',
		rethinkdb: {
			host: rethinkdb.host,
			port: rethinkdb.port,
			user: rethinkdb.username,
			password: rethinkdb.password,
			db: rethinkdb.database,
			silent: true,
			timeout: 30
		}
	},
	regexPrefix: new RegExp(/^((?:Hey |Ok )?Sistine(?:,|!))/i),
	console: { useColor: true, timestamps: 'MM-DD-YYYY hh:mm:ss A' },
	pieceDefaults: {
		commands: { deletable: true, cooldown: 3 },
		rawEvents: { enabled: true }
	}
};

module.exports.CatFacts = [
	"A cat's appetite is the barometer of its health. Any cat that does not eat or drink for more than two days should be taken to a vet.",
	"The cat's front paw has 5 toes, but the back paws have 4. Some cats are born with as many as 7 front toes and extra back toes (polydactl).",
	"A cat's whiskers are thought to be a kind of radar, which helps a cat gauge the space it intends to walk through.",
	'Cats and kittens should be acquired in pairs whenever possible as cat families interact best in pairs.',
	'Relative to its body size, the clouded leopard has the biggest canines of all animalsâ€™ canines. Its dagger-like teeth can be as long as 1.8 inches (4.5 cm).',
	'The oldest cat to give birth was Kitty who, at the age of 30, gave birth to two kittens. During her life, she gave birth to 218 kittens.',
	'The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer. Some cats have been documented to have a longevity of 34 years.',
	'The first commercially cloned pet was a cat named "Little Nicky." He cost his owner $50,000, making him one of the most expensive cats ever.',
	'The normal body temperature of a cat is between 100.5 Â° and 102.5 Â°F. A cat is sick if its temperature goes below 100 Â° or above 103 Â°F.',
	'Lions are the only cats that live in groups, called prides. Every female within the pride is usually related.',
	'In ancient Egypt, mummies were made of cats, and embalmed mice were placed with them in their tombs. In one ancient city, over 300,000 cat mummies were found.',
	'Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens, of which 15 survived.',
	'When your cats rubs up against you, she is actually marking you as \\hers\\" with her scent. If your cat pushes his face against your head"',
	'The largest cat breed is the Ragdoll. Male Ragdolls weigh between 12 and 20 lbs (5.4-9.0 k). Females weigh between 10 and 15 lbs (4.5-6.8 k).',
	'A catâ€™s brain is biologically more similar to a human brain than it is to a dogâ€™s. Both humans and cats have identical regions in their brains that are responsible for emotions.',
	'In Siam, the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.',
	'Since cats are so good at hiding illness, even a single instance of a symptom should be taken very seriously.',
	'A cat rubs against people not only to be affectionate but also to mark out its territory with scent glands around its face. The tail area and paws also carry the catâ€™s scent.',
	'Cats have 32 muscles that control the outer ear (humans have only 6). A cat can independently rotate its ears 180 degrees.',
	'You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.',
	'The Egyptian Mau is probably the oldest breed of cat. In fact, the breed is so ancient that its name is the Egyptian word for â€œcat.â€',
	'Female cats tend to be right pawed, while male cats are more often left pawed. Interestingly, while 90% of humans are right handed, the remaining 10% of lefties also tend to be male.',
	'A cat sees about 6 times better than a human at night, and needs 1/6 the amount of of light that a human does - it has a layer of extra reflecting cells which absorb light.',
	'Some common houseplants poisonous to cats include: English Ivy, iris, mistletoe, philodendron, and yew.',
	'In ancient Egypt, when a family cat died, all family members would shave their eyebrows as a sign of mourning.',
	'While many parts of Europe and North America consider the black cat a sign of bad luck, in Britain and Australia, black cats are considered lucky.',
	'In 1888, more than 300,000 mummified cats were found an Egyptian cemetery. They were stripped of their wrappings and carted off to be used by farmers in England and the U.S. for fertilizer.',
	'Cats should not be fed tuna exclusively, as it lacks taurine, an essential nutrient required for good feline health.  Make sure you have the proper Pet supplies to keep your cat happy and healthy.',
	'The most popular pedigreed cat is the Persian cat, followed by the Main Coon cat and the Siamese cat.',
	'According to Hebrew legend, Noah prayed to God for help protecting all the food he stored on the ark from being eaten by rats. In reply, God made the lion sneeze, and out popped a cat.',
	'Purring does not always indicate that a cat is happy. Cats will also purr loudly when they are distressed or in pain.',
	'Retractable claws are a physical phenomenon that sets cats apart from the rest of the animal kingdom. I n the cat family, only cheetahs cannot retract their claws.',
	'Cats can predict earthquakes. We humans are not 100% sure how they do it. There are several different theories.',
	'Grown cats have 30 teeth. Kittens have about 26 temporary teeth, which they lose when they are about 6 months old.',
	'Most cats had short hair until about 100 years ago, when it became fashionable to own cats and experiment with breeding.',
	'In 1987, cats overtook dogs as the number one pet in America (about 50 million cats resided in 24 million homes in 1986). About 37% of American homes today have at least one cat.',
	'In just 7 years, one un-spayed female cat and one un-neutered male cat and their offspring can result in 420,000 kittens.',
	'On average, cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life.',
	'The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet (3.6 m) long (about the size of a small car) and weigh up to 700 pounds (317 kg).',
	'A catâ€™s back is extremely flexible because it has up to 53 loosely fitting vertebrae. Humans only have 34.',
	'A cat almost never meows at another cat, mostly just humans. Cats typically will spit, purr, and hiss at other cats.',
	'The heaviest cat on record is Himmy, a Tabby from Queensland, Australia. He weighed nearly 47 pounds (21 kg). He died at the age of 10.',
	"The way you treat kittens in the early stages of it's life will render it's personality traits later in life.",
	'Tabby cats are thought to get their name from Attab, a district in Baghdad, now the capital of Iraq.',
	'The silks created by weavers in Baghdad were inspired by the beautiful and varied colors and markings of cat coats. These fabrics were called \\tabby\\" by European traders."""',
	'The smallest wildcat today is the Black-footed cat. The females are less than 20 inches (50 cm) long and can weigh as little as 2.5 lbs (1.2 kg).',
	'A cat called Dusty has the known record for the most kittens. She had more than 420 kittens in her lifetime.',
	'Cat families usually play best in even numbers. Cats and kittens should be acquired in pairs whenever possible.',
	'All cats need taurine in their diet to avoid blindness. Cats must also have fat in their diet as they are unable to produce it on their own.',
	'There are approximately 60,000 hairs per square inch on the back of a cat and about 120,000 per square inch on its underside.',
	'Cats are extremely sensitive to vibrations. Cats are said to detect earthquake tremors 10 or 15 minutes before humans can.',
	'Cats can be taught to walk on a leash, but a lot of time and patience is required to teach them. The younger the cat is, the easier it will be for them to learn.',
	'Unlike humans, cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.',
	'A cat has 230 bones in its body. A human has 206. A cat has no collarbone, so it can fit through any opening the size of its head.',
	'In just seven years, a single pair of cats and their offspring could produce a staggering total of 420,000 kittens.',
	'Cats have 30 teeth (12 incisors, 10 premolars, 4 canines, and 4 molars), while dogs have 42. Kittens have baby teeth, which are replaced by permanent teeth around the age of 7 months.',
	'A catâ€™s hearing is better than a dogâ€™s. And a cat can hear high-frequency sounds up to two octaves higher than a human.',
	'Cat families usually play best in even numbers. Cats and kittens should be aquired in pairs whenever possible.',
	'A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds, slightly less for female housecats.',
	'A commemorative tower was built in Scotland for a cat named Towser, who caught nearly 30,000 mice in her lifetime.',
	'A female cat will be pregnant for approximately 9 weeks or between 62 and 65 days from conception to delivery.',
	'Long, muscular hind legs enable snow leopards to leap seven times their own body length in a single bound.',
	'A cat has more bones than a human; humans have 206, but the cat has 230 (some cites list 245 bones, and state that bones may fuse together as the cat ages).',
	'A cat uses its whiskers for measuring distances.  The whiskers of a cat are capable of registering very small changes in air pressure.',
	'Cats have 30 vertebrae (humans have 33 vertebrae during early development; 26 after the sacral and coccygeal regions fuse)',
	"The chlorine in fresh tap water irritates sensitive parts of the cat's nose. Let tap water sit for 24 hours before giving it to a cat.",
	'Cats are North Americaâ€™s most popular pets: there are 73 million cats compared to 63 million dogs. Over 30% of households in North America own a cat.',
	'The most expensive cat was an Asian Leopard cat (ALC)-Domestic Shorthair (DSH) hybrid named Zeus. Zeus, who is 90% ALC and 10% DSH, has an asking price of Â£100,000 ($154,000).',
	'Miacis, the primitive ancestor of cats, was a small, tree-living creature of the late Eocene period, some 45 to 50 million years ago.',
	'Cats do not think that they are little people. They think that we are big cats. This influences their behavior in many ways.',
	'There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.',
	"Tests done by the Behavioral Department of the Musuem of Natural History conclude that while a dog's memory lasts about 5 minutes, a cat's recall can last as long as 16 hours.",
	'If a cat is frightened, the hair stands up fairly evenly all over the body; when the cat is threatened or is ready to attack, the hair stands up only in a narrow band along the spine and tail.',
	'People who are allergic to cats are actually allergic to cat saliva or to cat dander. If the resident cat is bathed regularly the allergic people tolerate it better.',
	'A cat named Dusty, aged 1 7, living in Bonham, Texas, USA, gave birth to her 420th kitten on June 23, 1952.',
	'The cat who holds the record for the longest non-fatal fall is Andy. He fell from the 16th floor of an apartment building (about 200 ft/.06 km) and survived.',
	"The domestic cat is the only species able to hold its tail vertically while walking. You can also learn about your cat's present state of mind by observing the posture of his tail.",
	"The cheetah is the world's fastest land mammal. It can run at speeds of up to 70 miles an hour (113 kilometers an hour).",
	'Cat paws act as tempetature regulators, shock absorbers, hunting and grooming tools, sensors, and more',
	'The tiniest cat on record is Mr. Pebbles, a 2-year-old cat that weighed 3 lbs (1.3 k) and was 6.1 inches (15.5 cm) high.',
	"Siamese kittens are born white because of the heat inside the mother's uterus before birth. This heat keeps the kittens' hair from darkening on the points.",
	'Cats sleep 16 to 18 hours per day. When cats are asleep, they are still alert to incoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.',
	'Contrary to popular belief, the cat is a social animal. A pet cat will respond and answer to speech , and seems to enjoy human companionship.',
	'The group of words associated with cat (catt,Â cath,Â chat,Â katze) stem from the LatinÂ catus, meaning domestic cat, as opposed toÂ feles, or wild cat.',
	'Not every cat gets \\high\\" from catnip. Whether or not a cat responds to it depends upon a recessive gene: no gene"',
	'Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.',
	'It may take as long as 2 weeks for a kitten to be able to hear well.  Their eyes usually open between 7 and 10 days, but sometimes it happens in as little as 2 days.',
	'The cat appears to be the only domestic companion animal not mentioned in the Bible.',
	'All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.',
	'Phoenician cargo ships are thought to have brought the first domesticated cats to Europe in about 900 BC.',
	"A cat's jaw has only up and down motion; it does not have any lateral, side to side motion, like dogs and humans.",
	"Cats, just like people, are subject to asthma. Dust, smoke, and other forms of air pullution in your cat's environment can be troublesome sources of irritation.",
	'Smuggling a cat out of ancient Egypt was punishable by death. Phoenician traders eventually succeeded in smuggling felines, which they sold to rich people in Athens and other important cities.',
	'A cat canâ€™t climb head first down a tree because every claw on a catâ€™s paw points the same way. To get down from a tree, a cat must back down.',
	'Mountain lions are strong jumpers, thanks to muscular hind legs that are longer than their front legs.',
	'Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do this more often, especially when they are excited.',
	'The claws on the catâ€™s back paws arenâ€™t as sharp as the claws on the front paws because the claws in the back donâ€™t retract and, consequently, become worn.',
	'Neutering a male cat will, in almost all cases, stop him from spraying (territorial marking), fighting with other males (at least over females), as well as lengthen his life and improve its quality.',
	'Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.',
	"Cats respond better to women than to men, probably due to the fact that women's voices have a higher pitch."
];

module.exports.DogFacts = [
	'Puppies have 28 teeth and adult dogs have 42.',
	'Hollywood’s first and arguably best canine superstar was Rin Tin Tin, a five-day-old German Shepherd found wounded in battle in WWI France and adopted by an American soldier, Lee Duncan. He would sign his own contracts with his paw print.',
	"Spiked dog collars were used to protect dogs' throats from wolf attacks in ancient Greece.",
	'Chocolate contains a substance known as theobromine (similar to caffeine) which can kill dogs or, at the very least, make them violently ill.',
	"A dog's whiskers are used as sensing devices.",
	'Dogs judge objects first by their movement, then by their brightness, and lastly by their shape.',
	"n ancient China, an emperor's last line of defense was a small Pekingese dog literally hidden up his sleeve.",
	'Greyhounds appear to be the most ancient dog breed. "Greyhound" comes from a mistake in translating the early German name Greishund, which means "old (or ancient) dog," not from the color gray.',
	'There are about 400 million dogs in the world.',
	'Dogs with little human contact in the first three months typically don’t make good pets.',
	'Endal was the first dog to ride on the London Eye (the characteristic ferris wheel in London, England), and was also the first known dog to successfully use a ATM machine.',
	'Dogs’ only sweat glands are between their paw pads.',
	'Dogs can count up to five and can perform simple mathematical calculations.',
	'Dogs can see best at dawn and dusk.',
	'Zorba, an English mastiff, is the biggest dog ever recorded. He weighed 343 pounds and measured 8’ 3" from his nose to his tail.',
	'Dogs have a wet nose to collect more of the tiny droplets of smelling chemicals in the air.',
	'It pays to be a lap dog. Three dogs (from First Class cabins!) survived the sinking of the Titanic – two Pomeranians and one Pekingese.',
	'A dog’s vision is not fully developed until after the first month.',
	'The smallest dog on record was a matchbox-size Yorkshire Terrier. It was 2.5" tall at the shoulder, 3.5" from nose tip to tail, and weighed only 4 ounces.',
	'The Beagle came into prominence in the 1300s and 1400s during the days of King Henry VII of England. Elizabeth I was fond of Pocket Beagles, which were only 9" high.',
	'Chase that tail! Dogs chase their tails for a variety of reasons: curiosity, exercise, anxiety, predatory instinct or, they might have fleas! If your dog is chasing his tail excessively, talk with your vet.',
	'Irish Wolfhounds, the tallest breed, are 30 to 35 inches tall.',
	'Growing up. While the Chow Chow dogs are well known for their distinctive blue-black tongues, they’re actually born with pink tongues. They turn blue-black at 8-10 weeks of age.',
	'Greyhounds are the fastest dogs on earth, with speeds of up to 45 miles per hour.',
	'Rock star Ozzy Osborne saved his wife Sharon’s Pomeranian from a coyote by tackling and wresting the coyote until it released the dog.',
	'In addition to "formal" forms of dog training (operant conditioning, reinforcement, or classical conditioning), dogs are able to learn merely from observation.',
	'Some dogs can smell dead bodies under water, where termites are hiding, and natural gas buried under 40 feet of dirt. They can even detect cancer that is too small to be detected by a doctor and can find lung cancer by sniffing a person’s breath.',
	'U.S. Customs dogs "Rocky" and "Barco" were so good at patrolling the border that Mexican drug lords put a $300,000 bounty on their heads.',
	'Different smells in the a dog’s urine can tell other dogs whether the dog leaving the message is female or male, old or young, sick or healthy, happy or angry.',
	'Dogs can see in color, though they most likely see colors similar to a color-blind human. They can see better when the light is low.',
	'One of Shakespeare’s most mischievous characters is Crab, the dog belonging to Launce in the Two Gentlemen of Verona. The word "watchdog" is first found in The Tempest.',
	'The oldest dog on record – a Queensland Heeler named Bluey – was 29 years, 5 months old.',
	'Teddy Roosevelt’s dog, Pete, ripped a French ambassador’s pants off at the White House.',
	'Obesity is the top health problem among dogs.',
	'The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.',
	'The Labrador Retriever has been the most popular dog breed since 1991.',
	'Dogs’ nose prints are as unique as a human’s finger prints, and can be used to accurately identify them.',
	'When "Bobbie," a Collie/Shepherd mix, was accidentally abandoned on a family vacation, he traveled 2,551 miles over six months to return to his home.',
	'Analysis of the dog genome demonstrate only 4 major types of dogs: "Old Lineage Dogs," "Mastiff-type Dogs," "Herding Dogs," and "Modern Hunting Dogs."',
	'Davy Crockett had a dog named Sport.',
	'Dogs live an average of 15 years.',
	'The dog was frequently depicted in Greek art, including Cerberus, the three-headed hound guarding the entrance to the underworld, and the hunting dogs which accompanied the virgin goddess of the chase, Diana.',
	'Puppies sleep 90% of the day for their first few weeks.',
	'Many foot disorders in dogs are simply an issue of too-long toenails.',
	'A Russian dog named Laika was the first animal in space, traveling around Earth in 1957.',
	'Move over Rover! 45% of dogs sleep in their owner’s bed (we’re pretty sure a large percentage also hog the blankets!)',
	'Dogs with a flesh colored nose is said to have a "Dudley Nose."',
	'Fifty-eight percent of people put pets in family and holiday portraits.',
	'The U.S. has the highest dog population in the world.',
	'Newfoundlands are great swimmers because of their webbed feet.',
	'The Berger Picard, Miniature American Shepherd and Lagotto Romagnolo are the newest dog breeds recognized by the American Kennel Club in 2015.',
	'During the Middle Ages, mixed breeds of peasants’ dogs were required to wear blocks around their necks to keep them from breeding with noble hunting dogs. Purebred dogs were very expensive and hunting became the province of the rich.',
	'The Chihuahua was named after the state in Mexico where they were discovered.',
	'Teams of dogs compete for the fastest time without errors in Flyball races.',
	'Three of the 12 dogs on the Titanic survived.',
	'Bichons, Portuguese Water Dogs, Kerry Blue Terriers, Maltese and Poodles are all good choices if you have allergies since they shed less than other breeds.',
	'Petting a dog can lower your blood pressure.',
	'One survey reports that 33% of dog owners admit they talk to their dogs on the phone or leave messages on answering machines while they are away..',
	'Dogs are naturally submissive to any creature with a higher pack status.',
	'Dogs are naturally submissive to any creature with higher pack status, human or canine.',
	'President Lyndon Johnson had two beagles named Him and Her.',
	'Humans can detect sounds at 20,000 times per second, while dogs can sense frequencies of 30,000 times per second.',
	'The most dogs ever owned by one person were 5,000 Mastiffs owned by Kublai Khan.',
	'There are an estimated 400 million dogs in the world.',
	'More than one in three U.S. families owns a dog.',
	"Dogs don't enjoy being hugged as much as humans and other primates. Canines interpret putting a limb over another animal as a sign of dominance.",
	'The phrase "raining cats and dogs" originated in 17th century England when it is believed that many cats and dogs drowned during heavy periods of rain.',
	'The ancient religion Zoroastrianism includes in its religious text titled the Zend Avesta a section devoted to the care and breeding of dogs.',
	'The bible mentions dogs 14 times.',
	'Boxers are so named because of their manner of playing using their front paws.',
	'During the Renaissance, detailed portraits of the dog as a symbol of fidelity and loyalty appeared in mythological, allegorical, and religious art throughout Europe, including works by Leonardo da Vinci, Diego Velázquez, Jan van Eyck, and Albrecht Durer.',
	'Petting dogs is proven to lower blood pressure of dog owners.',
	'Smaller breeds mature faster than larger breeds.',
	'Dogs have no sense of time.',
	'In 2001, it was estimated that there are approximately 400 million dogs in the world.',
	'At the end of WWI, the German government trained the first guide dogs for war-blinded soldiers.',
	'Dogs sleep for an average of 10 hours per day.',
	'Dogs have been used since the 1700’s for therapy.',
	'Smaller breeds of dogs mature faster than larger breeds.',
	'A dog’s pregnancy lasts for approximately 60 days.',
	'Seventy percent of people sign their pet’s name on greeting and holiday cards.',
	'French poodles did not originate in France but in Germany ("poodle" comes from the German pudel or pudelhund, meaning "splashing dog"). Some scholars speculate the poodle’s puffs of hair evolved when hunters shaved the poodle for more efficient swimming, while leaving the pom-poms around the major joints to keep them warm.',
	'In 1957, Laika became the first living being in space via an earth satellite and JFK’s terrier, Charlie, fathered 4 puppies with Laika’s daughter.',
	'The most popular dog breed in Canada, U.S., and Great Britain is the Labrador retriever.',
	"Although it was once illegal to keep dogs as pets in Iceland's capital city, the laws have been relaxed.",
	'The Basenji is the only barkless dog.',
	'Dogs are capable of understanding up to 250 words and gestures, can count up to five and can perform simple mathematical calculations. The average dog is as intelligent as a two-year-old child.',
	'Basset Hounds cannot swim.',
	'The phrase "raining cats and dogs" originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.',
	'The Labrador is so popular, in 2006 there were approximately 3-5 times more Labs as there were German Shepherds or Golden Retrievers.',
	'Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.',
	'Even with their poor eyesight, dogs can still see better at night than humans do.',
	'An elderly woman was saved by her 12-pound Yorkshire Terrier, who fought off an 80- pound Akita, and survived with only 9 stitches.',
	'Unlike cats, dogs are not exclusively carnivores: they can adapt to different foods, and a percentage of their diets can be fruits and vegetables.',
	'Female wolves have been known to travel great distances to regurgitate full meals for their hungry pups.',
	'There are hundreds of breeds of dogs.',
	'In Egypt, a person bitten by a rabid dog was encouraged to eat the roasted liver of a dog infected with rabies to avoid contracting the disease. The tooth of a dog infected with rabies would also be put in a band tied to the arm of the person bitten. The menstrual blood of a female dog was used for hair removal, while dog genitals were used for preventing the whitening of hair.',
	'Dogs can get jealous when their humans display affection toward someone or something else.',
	'Weird dog laws include allowing police offers in Palding, Ohio, to bite a dog to quiet it. In Ventura County, California, cats and dogs are not allowed to have sex without a permit.',
	'The largest dog was an English Mastiff who weighed 343 pounds.'
];

module.exports.Pickuplines = [
	'Are you French because Eiffel for you.',
	'Is that a mirror in your pocket? Cause I can see myself in your pants!',
	'Are you religious? Cause you’re the answer to all my prayers.',
	'Hey, tie your shoes! I don’t want you falling for anyone else.',
	'You must be Jamaican, because Jamaican me crazy.',
	'What has 36 teeth and holds back the Incredible Hulk? My zipper.',
	'Somebody call the cops, because it’s got to be illegal to look that good!',
	"I must be a snowflake, because I've fallen for you.",
	"I know you're busy today, but can you add me to your to-do list?",
	'If you were a steak you would be well done.',
	"Hello, I'm a thief, and I'm here to steal your heart.",
	'Are you cake? Cause I want a piece of that.',
	"My love for you is like diarrhoea, I just can't hold it in.",
	"Are you lost ma'am? Because heaven is a long way from here.",
	"There is something wrong with my cell phone. It doesn't have your number in it.",
	'If you were a library book, I would check you out.',
	"Are you a cat because I'm feline a connection between us",
	'If I were to ask you out on a date, would your answer be the same as the answer to this question?',
	'If nothing lasts forever, will you be my nothing?',
	"I'm new in town. Could you give me directions to your apartment?",
	'I must be in a museum, because you truly are a work of art.',
	'You spend so much time in my mind, I should charge you rent.',
	'My lips are like skittles. Wanna taste the rainbow?',
	'Well, here I am. What were your other two wishes?',
	"Are you from Tennessee? Because you're the only 10 I see!",
	'Are you a beaver? Cause daaaaaaaaam!',
	'Life without you is like a broken pencil... pointless.',
	'Do you want to see a picture of a beautiful person? (hold up a mirror)',
	"Is your body from McDonald's? Cause I'm lovin' it!",
	"Even if there wasn't gravity on earth, I'd still fall for you.",
	'Roses are red, violets are blue, how would you like it if I came home with you?',
	'I wish I were cross-eyed so I can see you twice',
	"We're not socks. But I think we'd make a great pair.",
	'Your lips look so lonely…Would they like to meet mine?',
	'Are you a parking ticket? ‘Cause you’ve got fine written all over you.',
	"Thank god I'm wearing gloves because you are too hot to handle.",
	"If a fat man puts you in a bag at night, don't worry I told Santa I wanted you for Christmas.",
	"I'm no photographer, but I can picture us together.",
	'Do your legs hurt from running through my dreams all night?',
	'Pinch me, you’re so fine I must be dreaming.',
	"If you were a chicken, you'd be impeccable.",
	'How much does a polar beat weight? Enough to break the ice!',
	'Are you a 90 degree angle? Cause you are looking right!',
	'Nice to meet you, I’m (your name) and you are... gorgeous!',
	'If I were a transplant surgeon, I’d give you my heart.',
	'Are you Israeli? Cause you Israeli hot.',
	"On a scale from 1 to 10, you're a 9... And I'm the 1 you need.",
	'Did it hurt? When you fell out of heaven?',
	'If I could rearrange the alphabet I would put U and I together.',
	'Remember me? Oh, that’s right, I’ve met you only in my dreams.',
	"Is your name Google? Because you've got everything I'm searching for.",
	'Your hand looks heavy. Here, let me hold it for you.',
	'I’ve been wondering, do your lips taste as good as they look.',
	'Are you from Starbucks because I like you a latte.',
	'Are you a banana because I find you a peeling.',
	'Do you like vegetables because I love you from my head tomatoes.',
	"Have you been to the doctor's lately? Cause I think you're lacking some vitamin me.",
	'Do you generate electricity with water through the process of hydro power? Because dammmm.',
	"Do you like science because I've got my ion you.",
	"Are you my appendix? Because I don't understand how you work but this feeling in my stomach makes me want to take you out.",
	"Do you like sales? Because if you're looking for a good one, clothing is 100% off at my place.",
	"I know this is going to sound cheesy, but I think you're the gratest.",
	"If you were a triangle you'd be acute one.",
	'Does your left eye hurt? Because you’ve been looking right all day.',
	'My feet are getting cold… because you’ve knocked my socks off.',
	'Wow, when god made you he was showing off.',
	'If beauty were time, you’d be eternity.',
	"Is your name Wi-fi? Because I'm really feeling a connection.",
	"If looks could kill, you'd be a weapon of mass destruction.",
	'Do you have a tan, or do you always look this hot?',
	'Can I follow you home? Cause my parents always told me to follow my dreams.',
	"If I were a cat I'd spend all 9 lives with you.",
	'Are you a camera? Because every time I look at you, I smile.',
	"Are you from Japan cause I'm trying to get in Japanties.",
	"If you were a fruit you'd be a fineapple.",
	"I'll give you a kiss. If you don't like it, you can return it.",
	"Did you swallow magnets? Cause you're attractive.",
	"Are you from China? Because I'm China get your number.",
	'Do you have a name, or can I call you mine?',
	'Are you craving Pizza? Because I’d love to get a pizz-a you',
	"Wouldn't we look cute on a wedding cake together.",
	"Would you grab my arm so I can tell my friends I've been touched by an angel?",
	"Kiss me if I'm wrong, but dinosaurs still exist, right?",
	'Is your dad a terrorist? Because you are the bomb.',
	'You must be a ninja, because you snuck into my heart',
	"Can you pinch me, because you're so fine I must be dreaming.",
	'I may not be a genie, but I can make all your wishes come true!',
	'Are you Australian? Because you meet all of my koala-fications.',
	'I’m not drunk, I’m just intoxicated by you.',
	'If I followed you home, would you keep me?',
	'If you were words on a page, you’d be fine print.',
	'Are you a keyboard ? Because you are my type.',
	'There is something wrong with my phone. Could you call it for me to see if it rings?',
	"I've seem to have lost my number, can I have yours?",
	'If I had a garden I’d put your tulips and my tulips together',
	"Did you hear of the new disease called beautiful, I think you're infected.",
	'I thought Happiness starts with H. But why does mine starts with U.',
	"If you were a vegetable you'd be a cutecumber.",
	'You know what you would really look beautiful in? My arms.',
	"My mom thinks I'm gay, can you help me prove her wrong?",
	'I want someone to look at me the way I look at chocolate cake.',
	'Is it hot in here or is it just you?',
	'Are you going to kiss me or do I have to lie to my diary?',
	'Feel my t-shirt, it’s made of boyfriend material.',
	'You must be a magician, because every time I look at you, everyone else disappears.',
	"Your name must be Coca Cola, because you're so-da-licious.",
	"You're like a dictionary... you add meaning to my life.",
	"My doctor says I'm lacking vitamin U.",
	'Did your licence get suspended for driving all these guys crazy?',
	'Do you believe in love at first sight or should I walk past again?',
	'When a penguin finds a mate they stay with them for the rest of their life. Will you be my penguin?',
	'Can I take a picture of you so santa knows what I want for christmas?',
	"I'm new in town, could you give me directions to your apartment?",
	"I'll cook you dinner, if you cook me breakfast",
	'What does it feel like to be the most beautiful girl in the room?',
	'Good thing I just bought term life insurance … because I saw you and my heart stopped!',
	'If I had a dollar for every time I thought of you, I’d be in a higher tax bracket.',
	'Hey, my name’s Microsoft. Can I crash at your place tonight?',
	'Was that an earthquake or did you just rock my world?',
	'You’re so sweet, you’re giving me a toothache.'
];

module.exports.MagicballAnswers = [
	'It is certain',
	'It is decidedly so',
	'Without a doubt',
	'Yes definitely',
	'You may rely on it',
	'As I see it, yes',
	'Most likely',
	'Outlook good',
	'Yes',
	'Signs point to yes',
	'Reply hazy try again',
	'Ask again later',
	'Better not tell you now',
	'Cannot predict now',
	'Concentrate and ask again',
	"Don't count on it",
	'My reply is no',
	'My sources say no',
	'Outlook not so good',
	'Very doubtful'
];

module.exports.Compliments = [
	'Your smile is contagious.',
	'You look great today.',
	"You're a smart cookie.",
	'I bet you make babies smile.',
	'You have impeccable manners.',
	'I like your style.',
	'You have the best laugh.',
	'I appreciate you.',
	'You are the most perfect you there is.',
	'You are enough.',
	"You're strong.",
	'Your perspective is refreshing.',
	"You're an awesome friend.",
	'You light up the room.',
	'You shine brighter than a shooting star.',
	'You deserve a hug right now.',
	'You should be proud of yourself.',
	"You're more helpful than you realize.",
	'You have a great sense of humor.',
	"You've got all the right moves!",
	"Is that your picture next to 'charming' in the dictionary?",
	'Your kindness is a balm to all who encounter it.',
	"You're all that and a super-size bag of chips.",
	"On a scale from 1 to 10, you're an 11.",
	'You are brave.',
	"You're even more beautiful on the inside than you are on the outside.",
	'You have the courage of your convictions.',
	'Your eyes are breathtaking.',
	'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.',
	'You are making a difference.',
	"You're like sunshine on a rainy day.",
	'You bring out the best in other people.',
	'Your ability to recall random factoids at just the right time is impressive.',
	"You're a great listener.",
	'How is it that you always look great, even in sweatpants?',
	'Everything would be better if more people were like you!',
	'I bet you sweat glitter.',
	'You were cool way before hipsters were cool.',
	'That color is perfect on you.',
	'Hanging out with you is always a blast.',
	'You always know -- and say -- exactly what I need to hear when I need to hear it.',
	'You smell really good.',
	"You may dance like no one's watching, but everyone's watching because you're an amazing dancer!",
	'Being around you makes everything better!',
	"When you say, 'I meant to do that,' I totally believe you.",
	"When you're not afraid to be yourself is when you're most incredible.",
	"Colors seem brighter when you're around.",
	"You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
	"That thing you don't like about yourself is what makes you so interesting.",
	"You're wonderful.",
	'You have cute elbows. For reals!',
	'Jokes are funnier when you tell them.',
	"You're better than a triple-scoop ice cream cone. With sprinkles.",
	'Your bellybutton is kind of adorable.',
	'Your hair looks stunning.',
	"You're one of a kind!",
	"You're inspiring.",
	"If you were a box of crayons, you'd be the giant name-brand one with the built-in sharpener.",
	'You should be thanked more often. So thank you!!',
	"Our community is better because you're in it.",
	"Someone is getting through something hard right now because you've got their back.",
	'You have the best ideas.',
	'You always know how to find that silver lining.',
	'Everyone gets knocked down sometimes, but you always get back up and keep going.',
	"You're a candle in the darkness.",
	"You're a great example to others.",
	'Being around you is like being on a happy little vacation.',
	'You always know just what to say.',
	"You're always learning new things and trying to better yourself, which is awesome.",
	'If someone based an Internet meme on you, it would have impeccable grammar.',
	'You could survive a Zombie apocalypse.',
	"You're more fun than bubble wrap.",
	'When you make a mistake, you fix it.',
	'Who raised you? They deserve a medal for a job well done.',
	"You're great at figuring stuff out.",
	'Your voice is magnificent.',
	'The people you love are lucky to have you in their lives.',
	"You're like a breath of fresh air.",
	"You're gorgeous -- and that's the least interesting thing about you, too.",
	"You're so thoughtful.",
	'Your creative potential seems limitless.',
	'Your name suits you to a T.',
	"You're irresistible when you blush.",
	'Actions speak louder than words, and yours tell an incredible story.',
	'Somehow you make time stop and fly at the same time.',
	'When you make up your mind about something, nothing stands in your way.',
	'You seem to really know who you are.',
	'Any team would be lucky to have you on it.',
	"In high school I bet you were voted 'most likely to keep being awesome.'",
	'I bet you do the crossword puzzle in ink.',
	'Babies and small animals probably love you.',
	"If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer).",
	"You're someone's reason to smile.",
	"You're even better than a unicorn, because you're real.",
	'How do you keep being so funny and making everyone laugh?',
	'You have a good head on your shoulders.',
	'Has anyone ever told you that you have great posture?',
	'The way you treasure your loved ones is incredible.',
	"You're really something special.",
	"You're a gift to those around you.",
	'You deserve better.'
];

module.exports.Insluts = {
	Start: ['a lazy', 'a stupid', 'an insecure', 'an idiotic', 'a slimy', 'a slutty', 'a smelly', 'a pompous', 'a communist', 'a dicknose', 'a pie-eating', 'a racist', 'an elitist', 'a white trash', 'a drug-loving', 'a butterface', 'a tone deaf', 'a ugly', 'a creepy', 'an artless', 'a bawdy', 'a beslubbering', 'a bootless', 'a churlish', 'a cockered', 'a clouted', 'a craven', 'a currish', 'a dankish', 'a dissembling', 'a droning', 'an errant', 'a fawning', 'a fobbing', 'a frothy', 'a gleeking', 'a goatfish', 'a gorbellied', 'an impertinent', 'an infectious', 'a jarring', 'a loggerheaded', 'a lumpish', 'a mammering', 'a mangled', 'a mewling', 'a paunchy', 'a pribbling', 'a puking', 'a puny', 'a qualling', 'a rank', 'a reeky', 'a roguish', 'a ruttish', 'a saucy', 'a spleeny', 'a spongy', 'a surly', 'a tottering', 'an unmuzzled', 'a vain', 'a venomed', 'a villainous', 'a warped', 'a wayward', 'a weedy', 'a yeasty', 'a lilly-livered', 'a rotten', 'a stinky', 'a lame', 'a dim-witted', 'a funky', 'a crusty', 'a steamy', 'a drizzly', 'a grizzly', 'a squirty', 'an uptight', 'a hairy', 'a husky', 'an arrogant', 'a nippy', 'a chunky', 'a smelly', 'a drooling', 'a crusty', 'a decrepic', 'a stupid', 'a moronic', 'a greasy', 'a poxy', 'an ugly', 'a smelly', 'a putrid', 'a shitty', 'an assinine', 'a sickening'],
	Middle: ['douche', 'ass', 'turd', 'rectum', 'butt', 'cock', 'shit', 'crotch', 'bitch', 'turd', 'prick', 'slut', 'taint', 'fuck', 'dick', 'boner', 'shart', 'nut', 'sphincter', 'base-court', 'bat-fowling', 'beef-witted', 'beetle-headed', 'boil-brained', 'clapper-clawed', 'clay-brained', 'common-kissing', 'crook-pated', 'dismal-dreaming', 'dizzy-eyed', 'doghearted', 'dread-bolted', 'earth-vexing', 'elf-skinned', 'fat-kidneyed', 'fen-sucked', 'flap-mouthed', 'fly-bitten', 'folly-fallen', 'fool-born', 'full-gorged', 'guts-gripping', 'half-faced', 'hasty-witted', 'hedge-born', 'hell-hated', 'idle-headed', 'ill-breeding', 'ill-nurtured', 'knotty-pated', 'milk-livered', 'motly-minded', 'onion-eyed', 'plume-plucked', 'pottle-deep', 'pox-marked', 'reeling-ripe', 'rough-hewn', 'rude-growing', 'rump-red', 'shard-borne', 'sheep-biting', 'spur-galled', 'swag-bellied', 'tardy-gaited', 'tickle-brained', 'toad-spotted', 'unchin-snouted', 'weather-bitten', 'hiney', 'poop', 'toot', 'wedgie', 'stool', 'fudge', 'bum', 'potty', 'dookie', 'pudding', 'sphincter', 'booger', 'feces', 'snot', 'crust', 'badonk-a', 'crud', 'sludge', 'tool', 'shit-kicking', 'monkey-licking', 'butt-munching', 'crotch-sniffing', 'donkey-spanking', 'fashion-illiterate', 'worm-ridden', 'grub-fucking', 'lathered-up', 'pasty-waisted', 'snot-flicking', 'fart-eating'],
	End: ['pilot', 'canoe', 'captain', 'pirate', 'hammer', 'knob', 'box', 'jockey', 'nazi', 'waffle', 'goblin', 'blossom', 'biscuit', 'clown', 'socket', 'monster', 'hound', 'dragon', 'balloon', 'apple-john', 'baggage', 'barnacle', 'bladder', 'boar-pig', 'bugbear', 'bum-bailey', 'canker-blossom', 'clack-dish', 'clotpole', 'coxcomb', 'codpiece', 'death-token', 'dewberry', 'flap-dragon', 'flax-wench', 'flirt-gill', 'foot-licker', 'fustilarian', 'giglet', 'gudgeon', 'haggard', 'harpy', 'hedge-pig', 'horn-beast', 'hugger-mugger', 'joithead', 'lewdster', 'lout', 'maggot-pie', 'malt-worm', 'mammet', 'measle', 'minnow', 'miscreant', 'moldwarp', 'mumble-news', 'nut-hook', 'pigeon-egg', 'pignut', 'puttock', 'pumpion', 'ratsbane', 'scut', 'skinsmate', 'strumpet', 'varlot', 'vassal', 'whey-face', 'wagtail', 'squeegee', 'turtle', 'cabbage', 'bomb', 'sniffer', 'binkie', 'stump', 'nugget', 'whistle', 'twig', 'knuckle', 'burger', 'hotdog', 'loaf', 'freckle', 'soldier', 'kernal', 'shingle', 'warrior', 'hemorrhoid', 'fuckface', 'asshole', 'scumbucket', 'toerag', 'hackwack', 'imbecile', 'stunodigan', 'maggot', 'hipster', 'gargabe', 'jerkstore']
};

module.exports.Penguins = [
	'http://i.imgur.com/Urfp335.png',
	'http://i.imgur.com/gC8v9fp.jpg',
	'http://i.imgur.com/DZ6YtvT.jpg',
	'http://i.imgur.com/LdWARAL.jpg',
	'http://i.imgur.com/7uF0u9Q.jpg',
	'http://i.imgur.com/0vgVnpr.png',
	'http://i.imgur.com/1GKlyH2.png',
	'http://i.imgur.com/jlzSELQ.png'
];

module.exports.Nsfw = {
	Boobs: [
		'http://media.oboobs.ru/boobs_preview/12280.jpg',
		'http://media.oboobs.ru/boobs_preview/12279.jpg',
		'http://media.oboobs.ru/boobs_preview/12278.jpg',
		'http://media.oboobs.ru/boobs_preview/12277.jpg',
		'http://media.oboobs.ru/boobs_preview/12276.jpg',
		'http://media.oboobs.ru/boobs_preview/12275.jpg',
		'http://media.oboobs.ru/boobs_preview/12274.jpg',
		'http://media.oboobs.ru/boobs_preview/12273.jpeg',
		'http://media.oboobs.ru/boobs_preview/12272.jpg',
		'http://media.oboobs.ru/boobs_preview/12271.jpg',
		'http://media.oboobs.ru/boobs_preview/12270.jpg',
		'http://media.oboobs.ru/boobs_preview/12269.jpg',
		'http://media.oboobs.ru/boobs_preview/12268.jpg',
		'http://media.oboobs.ru/boobs_preview/12267.jpg',
		'http://media.oboobs.ru/boobs_preview/12266.jpg',
		'http://media.oboobs.ru/boobs_preview/12265.jpg',
		'http://media.oboobs.ru/boobs_preview/12264.jpg',
		'http://media.oboobs.ru/boobs_preview/12263.jpg',
		'http://media.oboobs.ru/boobs_preview/12262.jpg',
		'http://media.oboobs.ru/boobs_preview/12261.jpg',
		'http://media.oboobs.ru/boobs_preview/12260.jpg',
		'http://media.oboobs.ru/boobs_preview/12259.jpg',
		'http://media.oboobs.ru/boobs_preview/12258.jpg',
		'http://media.oboobs.ru/boobs_preview/12257.jpg',
		'http://media.oboobs.ru/boobs_preview/12256.jpg',
		'http://media.oboobs.ru/boobs_preview/12255.jpg',
		'http://media.oboobs.ru/boobs_preview/12254.jpg',
		'http://media.oboobs.ru/boobs_preview/12253.jpg',
		'http://media.oboobs.ru/boobs_preview/12252.jpg',
		'http://media.oboobs.ru/boobs_preview/12251.jpg',
		'http://media.oboobs.ru/boobs_preview/12250.jpg',
		'http://media.oboobs.ru/boobs_preview/12249.jpg',
		'http://media.oboobs.ru/boobs_preview/12248.jpg',
		'http://media.oboobs.ru/boobs_preview/12247.jpg',
		'http://media.oboobs.ru/boobs_preview/12246.jpg',
		'http://media.oboobs.ru/boobs_preview/12245.jpg',
		'http://media.oboobs.ru/boobs_preview/12244.jpg',
		'http://media.oboobs.ru/boobs_preview/12243.jpg',
		'http://media.oboobs.ru/boobs_preview/12242.jpg',
		'http://media.oboobs.ru/boobs_preview/12241.jpg',
		'http://media.oboobs.ru/boobs_preview/12240.jpg',
		'http://media.oboobs.ru/boobs_preview/00327.jpg',
		'https://i.imgur.com/twUaMxG.jpg',
		'https://i.imgur.com/M8pzxWe.gif',
		'https://i.imgur.com/4zIlEXW.jpg',
		'https://i.imgur.com/ijdqR7y.jpg',
		'https://i.imgur.com/vuDQYbD.jpg',
		'https://i.imgur.com/Lrnz0nD.jpg',
		'https://i.imgur.com/LFOWorv.gif',
		'https://i.imgur.com/m7AmgRA.gif',
		'https://i.imgur.com/5km4kjw.jpg',
		'https://i.imgur.com/SD57zlE.jpg',
		'https://i.imgur.com/8ShaWOP.jpg',
		'https://i.imgur.com/zwWw04x.jpg',
		'https://i.imgur.com/S2VmpFt.jpg',
		'https://i.imgur.com/f5GEjLW.jpg',
		'https://i.imgur.com/OFLDgVn.jpg',
		'https://i.imgur.com/CUy3EPa.gif',
		'https://i.imgur.com/X1fFQCf.jpg',
		'https://i.imgur.com/r6cYucx.jpg',
		'https://i.imgur.com/YJhHLPt.jpg',
		'https://i.imgur.com/ZU7jSKT.gif',
		'https://i.imgur.com/rUsnn3e.gif',
		'https://i.imgur.com/KyDfD2Q.gif',
		'https://i.imgur.com/EpzpHbE.gif',
		'https://i.imgur.com/YdoThF9.gif',
		'https://i.imgur.com/SDkIcbI.gif',
		'https://i.imgur.com/dxBHH56.jpg',
		'https://i.imgur.com/XUf3d7g.gif',
		'https://i.imgur.com/RF9tiCI.jpg',
		'https://i.imgur.com/DsX9KBH.gif',
		'https://i.imgur.com/fQiZZmV.gif',
		'https://i.imgur.com/zyXRmGn.jpg',
		'https://i.imgur.com/0fbEVa6.jpg',
		'https://i.imgur.com/3xa6gkA.jpg',
		'https://i.imgur.com/DZjdCNa.jpg',
		'https://i.imgur.com/wknHT43.jpg',
		'https://i.imgur.com/PQOz8Ii.jpg',
		'https://i.imgur.com/IrxuE8r.jpg',
		'https://i.imgur.com/5u9rjB1.gif',
		'https://i.imgur.com/Y22LzVt.jpg',
		'https://i.imgur.com/trbXz5k.jpg',
		'https://i.imgur.com/6X5Ji1x.jpg',
		'https://i.imgur.com/ywAfdLI.jpg',
		'https://i.imgur.com/q2C2deq.jpg',
		'https://imgur.com/a/CM3Wd',
		'https://i.imgur.com/sR6pJcz.gif',
		'https://i.imgur.com/DWuUnGR.jpg',
		'https://i.imgur.com/BRqhe2h.jpg',
		'https://i.imgur.com/VW39lx1.jpg',
		'https://i.imgur.com/moQUYxH.gif',
		'https://i.imgur.com/0PCHCkA.gif',
		'https://i.imgur.com/zc2v3OP.gif',
		'https://i.imgur.com/eW3zei4.jpg',
		'https://i.imgur.com/IaDvDfw.jpg',
		'https://i.imgur.com/YGirIhl.jpg',
		'https://i.imgur.com/OHyYqyX.jpg',
		'https://i.imgur.com/KyJYoYV.jpg',
		'https://i.imgur.com/HAemYgQ.jpg',
		'https://i.imgur.com/xe2okgi.jpg',
		'https://i.imgur.com/nvvteL1.gif',
		'https://i.imgur.com/mAud2tX.jpg',
		'https://i.imgur.com/El4sa5N.jpg',
		'https://i.imgur.com/OOuLNhf.jpg',
		'https://i.imgur.com/KvVlcAK.jpg',
		'https://i.imgur.com/VkrOWoV.jpg',
		'https://i.imgur.com/XZ8xIHe.jpg',
		'https://i.imgur.com/eZSL5Wq.jpg',
		'https://i.imgur.com/lpfXYrl.jpg',
		'https://i.imgur.com/FoNAg9V.jpg',
		'https://i.imgur.com/KbLvWRF.jpg',
		'https://i.imgur.com/ZwQKDOO.jpg',
		'https://i.imgur.com/qv9nn4s.jpg',
		'https://i.imgur.com/jZ1aIok.jpg',
		'https://i.imgur.com/MYkvcgd.jpg',
		'https://i.imgur.com/VhAQHCw.gif',
		'https://i.imgur.com/f4plVRc.jpg',
		'https://i.imgur.com/Ni2G5Zp.jpg',
		'https://i.imgur.com/4pO2M3U.jpg',
		'https://i.imgur.com/6XUw7ti.jpg',
		'https://i.imgur.com/LkPDbbX.jpg',
		'https://i.imgur.com/7oPtCH5.jpg',
		'https://i.imgur.com/eHU2GGo.jpg',
		'https://i.imgur.com/HUWjoXb.png',
		'https://i.imgur.com/PaKlX8t.jpg',
		'https://i.imgur.com/rGvSiGK.jpg',
		'https://i.imgur.com/jxT1XOB.jpg',
		'https://i.imgur.com/oQnB7Kd.jpg',
		'https://i.imgur.com/AHkPKzq.jpg',
		'https://i.imgur.com/OmerYKv.gif',
		'http://i.imgur.com/z3sIRlZh.gif',
		'https://i.imgur.com/Cj6AvUc.jpg',
		'https://i.imgur.com/h0JKPai.gif',
		'https://i.imgur.com/qXdm1gE.jpg',
		'https://i.imgur.com/sCstHKD.jpg',
		'https://i.imgur.com/2vO1IKu.jpg',
		'https://i.imgur.com/0vEZzTJ.jpg',
		'https://i.imgur.com/GuxgYOR.jpg',
		'https://i.imgur.com/BMJTb3P.jpg',
		'https://i.imgur.com/xPrwb7O.jpg',
		'https://i.imgur.com/QUMSbME.jpg',
		'https://i.imgur.com/XRQxsE0.jpg',
		'https://i.imgur.com/yRS0bzL.jpg',
		'https://i.imgur.com/KjRme5I.jpg',
		'https://i.imgur.com/AeXEoR9.jpg',
		'https://i.imgur.com/z8FUXm8.jpg',
		'https://i.imgur.com/Tf0BgBq.jpg',
		'https://i.imgur.com/VRpwRON.jpg',
		'https://i.imgur.com/r18DzWR.jpg',
		'https://i.imgur.com/fLTJAU4.jpg',
		'https://i.imgur.com/tA41cL0.jpg',
		'https://imgur.com/a/EbpKY',
		'https://i.imgur.com/FkqOa5m.jpg',
		'https://i.imgur.com/RFHPoye.jpg',
		'https://i.imgur.com/yXoMut2.jpg',
		'http://i.imgur.com/GD6Py8zh.gif',
		'https://i.imgur.com/Mqxigbz.jpg',
		'https://i.imgur.com/Ua1r98T.jpg',
		'https://i.imgur.com/KKtz4iM.jpg',
		'https://i.imgur.com/AyPioAl.jpg',
		'https://i.imgur.com/CIhlH2e.jpg',
		'https://i.imgur.com/dVFjERu.jpg',
		'https://imgur.com/a/1s0HO',
		'https://i.imgur.com/2USf5Cy.jpg',
		'https://i.imgur.com/lzflXEC.jpg',
		'https://i.imgur.com/izOLMhB.jpg',
		'https://i.imgur.com/TmzNRuz.jpg',
		'https://i.imgur.com/ZCeTQSb.jpg',
		'https://i.imgur.com/CO7A5V3.jpg',
		'https://i.imgur.com/0NQDyYK.jpg',
		'https://i.imgur.com/GqO08LN.jpg',
		'https://i.imgur.com/VZuGmfD.jpg',
		'https://i.imgur.com/mGyq6ik.jpg',
		'https://i.imgur.com/tnRUrBr.jpg',
		'https://i.imgur.com/x7AvI5T.jpg',
		'https://i.imgur.com/7bqMAgw.jpg',
		'https://i.imgur.com/77iUAvr.jpg',
		'https://i.imgur.com/2wPEQgz.jpg',
		'https://i.imgur.com/TKDTBYJ.jpg',
		'https://i.imgur.com/KPJIqyZ.jpg',
		'https://i.imgur.com/MwLgRTw.jpg',
		'https://i.imgur.com/CHhrCAR.jpg',
		'https://i.imgur.com/eNmJfJ3.jpg',
		'https://i.imgur.com/CZ4LIUr.jpg',
		'https://i.imgur.com/hYDFsez.jpg',
		'https://i.imgur.com/hXDexrM.jpg',
		'https://i.imgur.com/qIKD8sv.jpg',
		'https://i.imgur.com/qIIKzIO.jpg',
		'https://i.imgur.com/U87onAD.jpg',
		'https://i.imgur.com/Raa44MF.jpg',
		'https://i.imgur.com/kCOi3ho.jpg',
		'http://i.imgur.com/G3qSJleh.gif',
		'https://i.imgur.com/fJQkhUZ.gif',
		'https://i.imgur.com/sRNOnkd.jpg',
		'https://i.imgur.com/5KYsurg.jpg',
		'https://i.imgur.com/xcZm5st.jpg',
		'https://i.imgur.com/GDmDTsQ.jpg',
		'https://i.imgur.com/sPyT5gs.jpg',
		'https://i.imgur.com/oFsAcrK.jpg',
		'https://i.imgur.com/UrnhLQK.jpg',
		'http://i.imgur.com/gskGj1Ph.gif',
		'https://i.imgur.com/sDyQNzW.png',
		'https://i.imgur.com/5gGQYYG.jpg',
		'https://i.imgur.com/8rmhp7t.jpg',
		'https://i.imgur.com/TtV5q3f.jpg',
		'https://i.imgur.com/u2hsdJJ.jpg',
		'https://i.imgur.com/MyL5rc2.jpg',
		'http://i.imgur.com/FmcOAFlh.gif',
		'https://i.imgur.com/BVeJpDm.gif',
		'https://i.imgur.com/lzZlfkw.jpg',
		'https://i.imgur.com/lPXtLpf.jpg',
		'https://i.imgur.com/Pky3O3o.jpg',
		'https://i.imgur.com/QegNrbB.jpg',
		'https://i.imgur.com/2x95six.gif',
		'https://i.imgur.com/RACKnKy.jpg',
		'https://i.imgur.com/rFeFY7A.jpg',
		'https://i.imgur.com/kGpSzfL.jpg',
		'https://i.imgur.com/wn2w7fv.jpg',
		'https://i.imgur.com/7JMg6DT.jpg',
		'https://i.imgur.com/INgDEQ5.jpg',
		'https://i.imgur.com/Oaql9Ap.jpg',
		'https://i.imgur.com/LUNSx7H.jpg',
		'https://i.imgur.com/kh6EnnJ.jpg',
		'https://i.imgur.com/JAXJ80O.jpg',
		'https://i.imgur.com/1TpnoI5.jpg',
		'https://i.imgur.com/DtlPtg1.jpg',
		'https://i.imgur.com/Ul00gmw.jpg',
		'https://i.imgur.com/6rh3b2o.jpg',
		'https://i.imgur.com/IA2uLIo.jpg',
		'https://i.imgur.com/w5m7QtO.jpg',
		'https://i.imgur.com/WHW9Cti.jpg',
		'https://i.imgur.com/BSWfWSA.jpg',
		'https://i.imgur.com/ztEHDBB.jpg',
		'https://i.imgur.com/hMLjHGF.jpg',
		'https://i.imgur.com/5cZcXCL.jpg',
		'https://i.imgur.com/MYuLh4h.jpg',
		'https://i.imgur.com/2DOVX7t.jpg',
		'http://i.imgur.com/mjYIv3Hh.gif',
		'https://i.imgur.com/RWe1IVs.jpg',
		'https://i.imgur.com/7enmpBA.jpg',
		'https://i.imgur.com/zmDtZrr.jpg',
		'https://i.imgur.com/EtdW3mM.jpg',
		'https://i.imgur.com/HirvDke.png',
		'https://i.imgur.com/NSatVB9.jpg',
		'https://i.imgur.com/GiTbqxm.jpg',
		'https://i.imgur.com/RYpL93Y.jpg',
		'https://i.imgur.com/4eKmmK8.jpg',
		'https://i.imgur.com/1SkqeDS.jpg',
		'https://i.imgur.com/Ym1TQAb.jpg',
		'https://i.imgur.com/UOkemJT.jpg',
		'https://i.imgur.com/Jc8LjuO.jpg',
		'https://i.imgur.com/JF1PgXZ.jpg',
		'https://i.imgur.com/EEsyQtO.jpg',
		'https://i.imgur.com/iEwBM7d.jpg',
		'https://i.imgur.com/1tvWKSY.jpg',
		'https://i.imgur.com/yXPgq7u.jpg',
		'https://i.imgur.com/kQqMyXD.jpg',
		'https://i.imgur.com/Uuhi3Aw.jpg',
		'https://i.imgur.com/zA1c60a.jpg',
		'https://i.imgur.com/PmsGZwY.jpg',
		'https://i.imgur.com/pfbrxcz.jpg',
		'https://i.imgur.com/BE5lcXa.jpg',
		'https://i.imgur.com/wk9FlgW.jpg',
		'https://i.imgur.com/4Cn2X7B.jpg',
		'https://i.imgur.com/RXhb4Vp.jpg',
		'https://i.imgur.com/Xhl8Qq3.jpg',
		'https://i.imgur.com/aPEzxyJ.jpg',
		'https://i.imgur.com/iO6Xm5Q.jpg',
		'https://i.imgur.com/hQMNy2a.jpg',
		'https://i.imgur.com/pzPePez.jpg',
		'https://i.imgur.com/C8Gjmmx.jpg',
		'https://i.imgur.com/Wobr9Xv.jpg',
		'https://i.imgur.com/cTTf2Hs.jpg',
		'https://i.imgur.com/MrwyYPL.jpg',
		'https://i.imgur.com/5a4apSP.jpg',
		'https://i.imgur.com/ARw6hzv.jpg',
		'https://i.imgur.com/mLO1dn7.jpg',
		'https://i.imgur.com/GZAl7mL.jpg',
		'https://i.imgur.com/VbMdbun.jpg',
		'https://i.imgur.com/rHG6YCQ.jpg',
		'https://i.imgur.com/iBSo0ij.jpg',
		'https://i.imgur.com/tyeh9An.jpg',
		'https://i.imgur.com/TpWZDiI.jpg',
		'https://i.imgur.com/yWIyaAL.jpg',
		'https://i.imgur.com/hIF8lZn.jpg',
		'https://i.imgur.com/R56dMVi.jpg',
		'https://i.imgur.com/rzmXc4g.jpg',
		'https://i.imgur.com/rWlPE5M.jpg',
		'https://i.imgur.com/i5dgoKO.jpg',
		'https://i.imgur.com/qxndZtz.png',
		'https://i.imgur.com/6hjNc4R.jpg',
		'https://i.imgur.com/weOViDr.jpg',
		'https://i.imgur.com/1E0TvZn.jpg',
		'https://i.imgur.com/j4iDWO3.jpg',
		'https://i.imgur.com/fdGx7Ej.jpg',
		'https://i.imgur.com/xlNGHV3.jpg',
		'https://i.imgur.com/svaHdDm.png',
		'https://i.imgur.com/6TJ407m.jpg',
		'https://i.imgur.com/dDtEYaI.jpg',
		'https://i.imgur.com/6k3fwrZ.jpg',
		'https://i.imgur.com/KnzcNNN.jpg',
		'https://i.imgur.com/QrSozHm.gif',
		'https://i.imgur.com/s3ZEDkD.jpg',
		'https://i.imgur.com/F5LqAUL.jpg',
		'https://i.imgur.com/PP4rBWs.jpg',
		'https://i.imgur.com/pSSvpZc.jpg',
		'https://i.imgur.com/LcEVAig.jpg',
		'https://i.imgur.com/d24Xtd4.jpg',
		'https://i.imgur.com/MDu7u2d.jpg',
		'https://i.imgur.com/Tcgmeg1.jpg',
		'https://i.imgur.com/KHQRPLv.jpg',
		'https://i.imgur.com/HZbOrF7.jpg',
		'https://i.imgur.com/poPQhed.jpg',
		'https://i.imgur.com/yxjj7Qe.jpg',
		'https://i.imgur.com/3p6CsWP.jpg',
		'https://i.imgur.com/uLPRBHy.jpg',
		'https://i.imgur.com/vxSMXHp.jpg',
		'https://i.imgur.com/7zJtUYS.jpg',
		'https://i.imgur.com/4YY0W7I.jpg',
		'https://i.imgur.com/eTAY17V.jpg',
		'https://i.imgur.com/OPKm5Y7.jpg',
		'https://i.imgur.com/89dksfi.jpg',
		'https://i.imgur.com/l1Km88I.jpg',
		'https://i.imgur.com/XxJXx5M.jpg',
		'https://i.imgur.com/aNb0OCI.jpg',
		'https://i.imgur.com/qT8zmsM.jpg',
		'https://i.imgur.com/mWvnSvt.jpg',
		'https://i.imgur.com/peeM6gR.png',
		'https://i.imgur.com/TL3KuBm.jpg',
		'https://i.imgur.com/4on6k18.png',
		'https://i.imgur.com/oZBxpr9.jpg',
		'https://i.imgur.com/zFABYi2.jpg',
		'https://i.imgur.com/kFOpOEj.jpg',
		'https://i.imgur.com/hq1xb8u.jpg',
		'https://i.imgur.com/OxvF1jf.jpg',
		'https://i.imgur.com/QENvV3s.jpg',
		'https://i.imgur.com/k3nk9VV.jpg',
		'https://i.imgur.com/F7y1lZt.jpg',
		'https://i.imgur.com/GIhtnOF.jpg',
		'https://i.imgur.com/xh1S3D4.jpg',
		'https://i.imgur.com/mqpqTx5.jpg',
		'https://i.imgur.com/01y7H8V.jpg',
		'https://i.imgur.com/tbfF2hJ.gif',
		'https://i.imgur.com/SECBKcS.jpg',
		'https://i.imgur.com/vslQatE.jpg',
		'https://i.imgur.com/INKkPoM.jpg',
		'https://i.imgur.com/KuqVGwD.gif',
		'https://i.imgur.com/Mxblxd3.jpg',
		'https://i.imgur.com/pD1wi8e.jpg',
		'https://i.imgur.com/GwN0bcC.jpg',
		'https://i.imgur.com/PBxaAQT.jpg',
		'https://i.imgur.com/KAfKG0X.jpg',
		'https://i.imgur.com/L1EmM9f.jpg',
		'https://i.imgur.com/1XFEHMK.jpg',
		'https://i.imgur.com/nOGKHV9.jpg',
		'https://i.imgur.com/44Iyt2w.jpg',
		'https://i.imgur.com/hgKGGYs.jpg',
		'https://i.imgur.com/bUJBSqf.jpg',
		'https://i.imgur.com/ssYJXSn.gif',
		'https://i.imgur.com/zHqDG2r.jpg',
		'https://i.imgur.com/P8v0m0T.jpg',
		'https://i.imgur.com/S9w0TiU.jpg',
		'https://i.imgur.com/aRUzuJY.jpg',
		'https://i.imgur.com/EfRZowj.gif',
		'https://i.imgur.com/WDtcg9J.jpg',
		'https://i.imgur.com/wZ3mXBX.jpg',
		'https://i.imgur.com/dB69W4H.jpg',
		'https://i.imgur.com/JRHszKy.jpg',
		'https://i.imgur.com/yPLZTAG.jpg',
		'https://i.imgur.com/WifBoga.jpg',
		'https://i.imgur.com/LPoqjKo.gif',
		'https://i.imgur.com/KCS41iS.jpg',
		'https://i.imgur.com/QeriCt1.jpg',
		'https://i.imgur.com/hEbvOe4.jpg',
		'https://i.imgur.com/9D0TTDo.jpg',
		'https://i.imgur.com/ixpaWEH.png',
		'https://i.imgur.com/9yKF1gd.jpg',
		'https://i.imgur.com/PxbrMw8.jpg',
		'https://i.imgur.com/aFqynjd.jpg',
		'https://i.imgur.com/P3MmgxW.jpg',
		'https://i.imgur.com/RvuoP8Y.jpg',
		'https://i.imgur.com/KdDjwwV.jpg',
		'https://i.imgur.com/N4xTZwd.jpg',
		'https://i.imgur.com/ovimEru.jpg',
		'https://i.imgur.com/O7gyEph.jpg',
		'https://i.imgur.com/s5QKfsH.jpg',
		'https://i.imgur.com/HO1Cc1p.jpg',
		'https://i.imgur.com/oj5x07v.jpg',
		'https://i.imgur.com/hVYGnTg.jpg',
		'http://i.imgur.com/d8xUyOth.gif',
		'https://i.imgur.com/kIAN1je.jpg',
		'https://i.imgur.com/V4y6SfX.jpg',
		'https://i.imgur.com/5mY8bxN.jpg',
		'https://i.imgur.com/xrGihT4.jpg',
		'https://i.imgur.com/bINGfXZ.jpg',
		'https://i.imgur.com/VKFPZEr.jpg',
		'https://i.imgur.com/8N2CW2o.jpg',
		'https://i.imgur.com/zJJeZAZ.png',
		'https://i.imgur.com/kyyJT2i.jpg',
		'https://i.imgur.com/Y0whrbm.gif',
		'https://i.imgur.com/ZB9G7hf.jpg',
		'https://i.imgur.com/XjseVZm.jpg',
		'https://i.imgur.com/wGiAeWI.png',
		'https://i.imgur.com/38umKVW.jpg',
		'https://i.imgur.com/EnjlUZb.gif',
		'https://i.imgur.com/JyZoLIW.jpg',
		'https://i.imgur.com/UT2hmDr.jpg',
		'https://i.imgur.com/GVCVqoX.jpg',
		'https://i.imgur.com/VONdmjW.jpg',
		'https://i.imgur.com/qGC9Jni.jpg',
		'https://i.imgur.com/glWBxYB.jpg',
		'https://i.imgur.com/nUkvMnP.jpg',
		'https://i.imgur.com/JXfYTOL.jpg',
		'https://i.imgur.com/oRZzIoc.jpg',
		'https://i.imgur.com/WASWADP.jpg',
		'https://i.imgur.com/oyz1q6S.jpg',
		'https://i.imgur.com/B1d0VfP.jpg',
		'https://i.imgur.com/J7DcvW6.jpg',
		'https://i.imgur.com/y7cHiqm.jpg',
		'https://i.imgur.com/sO2B8Ef.jpg',
		'https://i.imgur.com/VtoDyuX.jpg',
		'https://imgur.com/a/NfGnM',
		'https://i.imgur.com/XL12D9m.jpg',
		'https://i.imgur.com/nr9T75C.jpg',
		'https://i.imgur.com/HMmzlYs.jpg',
		'https://i.imgur.com/WeNe8B2.jpg',
		'https://i.imgur.com/3HUn18o.jpg',
		'https://i.imgur.com/Cmowwh6.jpg',
		'https://i.imgur.com/N4mAli7.jpg',
		'https://i.imgur.com/xMGWoKI.gif',
		'https://i.imgur.com/DqIlcEv.jpg',
		'https://i.imgur.com/dVWECec.jpg',
		'https://i.imgur.com/G6T4lb1.jpg',
		'https://i.imgur.com/GCf0nNw.jpg',
		'https://i.imgur.com/ubbcyWn.jpg',
		'https://i.imgur.com/K6kqOsM.jpg',
		'https://i.imgur.com/iUEtmlM.jpg',
		'https://i.imgur.com/saXsyFc.png',
		'https://i.imgur.com/FClaBrw.jpg',
		'https://i.imgur.com/MCvFHw0.gif',
		'https://i.imgur.com/G4yKRhA.jpg',
		'https://i.imgur.com/4oW3dZy.jpg',
		'https://i.imgur.com/rlxqFne.jpg',
		'https://i.imgur.com/54DCAcM.jpg',
		'https://i.imgur.com/6RUvyJw.jpg',
		'https://i.imgur.com/IPZMPvl.jpg',
		'https://i.imgur.com/biyVatH.jpg',
		'https://i.imgur.com/gBcv03u.jpg',
		'https://i.imgur.com/AdDjPng.jpg',
		'https://i.imgur.com/ZzUAHSi.jpg',
		'https://i.imgur.com/XvdDF71.jpg',
		'https://i.imgur.com/kwyrv4H.jpg',
		'https://i.imgur.com/OyGJVx9.jpg',
		'https://i.imgur.com/iLtoHbv.jpg',
		'https://i.imgur.com/UpEYkEx.jpg',
		'https://i.imgur.com/z2rl4Cm.jpg',
		'https://i.imgur.com/FcS9dxk.jpg',
		'https://i.imgur.com/8M0pv27.jpg',
		'https://i.imgur.com/n5UERJL.jpg',
		'https://i.imgur.com/aQhVESv.jpg',
		'https://i.imgur.com/chYimVz.jpg',
		'https://i.imgur.com/6CHlM1k.jpg',
		'https://i.imgur.com/VO7wqd9.jpg',
		'https://i.imgur.com/mT2pmBh.jpg',
		'https://i.imgur.com/HuKSurJ.jpg',
		'https://i.imgur.com/diMAdzy.jpg',
		'https://i.imgur.com/G6JiedS.jpg',
		'https://i.imgur.com/CyeUoCE.jpg',
		'https://imgur.com/a/d8MZ1',
		'https://i.imgur.com/kMVq7cq.jpg',
		'https://i.imgur.com/gXe8Dm1.jpg',
		'https://i.imgur.com/VLSBxXN.jpg',
		'https://i.imgur.com/EhThGPU.jpg',
		'https://i.imgur.com/5QqpjGb.jpg',
		'https://i.imgur.com/dN6UheR.jpg',
		'https://i.imgur.com/VUGBcoA.jpg',
		'https://i.imgur.com/lkzVym0.jpg',
		'https://i.imgur.com/FeEgP3Q.png',
		'https://i.imgur.com/l3OTvt4.jpg',
		'https://i.imgur.com/8bBaBw0.jpg',
		'https://i.imgur.com/WeszvET.jpg',
		'https://i.imgur.com/GcxYFmD.jpg',
		'https://i.imgur.com/Xxa5NkH.jpg',
		'https://i.imgur.com/1EmuhEZ.png',
		'https://i.imgur.com/eGkBOyF.jpg',
		'https://i.imgur.com/Vw4g4xZ.jpg',
		'https://i.imgur.com/3vMVcL5.gif',
		'https://i.imgur.com/cg7avhP.jpg',
		'https://i.imgur.com/tXndygN.jpg',
		'https://i.imgur.com/xEju3fn.jpg',
		'https://i.imgur.com/UXyvUbY.jpg',
		'https://i.imgur.com/ThTC6v8.jpg',
		'https://i.imgur.com/hvuTZY4.jpg',
		'https://i.imgur.com/Ru9enPP.jpg',
		'https://i.imgur.com/Xoz5RL7.jpg',
		'https://i.imgur.com/Q6D41tE.jpg',
		'https://i.imgur.com/ZEEJaT9.jpg',
		'https://i.imgur.com/tU26Qsn.jpg',
		'https://i.imgur.com/gxdnESM.jpg',
		'https://i.imgur.com/4WznBEN.jpg',
		'https://i.imgur.com/tMucU8j.jpg',
		'https://i.imgur.com/JKU1rDF.jpg',
		'https://i.imgur.com/ertVDv3.jpg',
		'https://i.imgur.com/r8ARUNl.jpg',
		'https://i.imgur.com/5nUwDnN.jpg',
		'https://i.imgur.com/IRiKQuO.jpg',
		'https://i.imgur.com/yrnZ6xb.png',
		'https://i.imgur.com/SwKBBXm.jpg',
		'https://i.imgur.com/YQhwzuT.jpg',
		'https://i.imgur.com/EXEd7ox.jpg',
		'https://i.imgur.com/ijZULde.jpg',
		'https://i.imgur.com/OtWcqFG.jpg',
		'https://i.imgur.com/rs6f0Co.jpg',
		'https://i.imgur.com/3PF0H78.jpg',
		'https://i.imgur.com/NSy2buG.jpg',
		'https://i.imgur.com/dUZlhrY.jpg',
		'https://i.imgur.com/9W0hMaM.jpg',
		'https://i.imgur.com/AEmXn16.jpg',
		'https://i.imgur.com/1UOWZzn.jpg',
		'https://i.imgur.com/05Bsowg.jpg',
		'https://i.imgur.com/0W7tbxu.jpg',
		'https://i.imgur.com/o4AJlqP.jpg',
		'https://i.imgur.com/YCe0zbX.jpg',
		'https://i.imgur.com/LIyvvE4.jpg',
		'https://i.imgur.com/aG5oNwc.jpg',
		'https://i.imgur.com/Zghvez4.jpg',
		'https://i.imgur.com/lGZYh4Y.jpg',
		'https://i.imgur.com/caOScQA.jpg',
		'https://i.imgur.com/eVuJ5Oo.jpg',
		'https://i.imgur.com/Vxdfmjc.jpg',
		'https://i.imgur.com/pfMr4ft.jpg',
		'https://i.imgur.com/9o1rfle.jpg',
		'https://i.imgur.com/6leXarI.jpg',
		'https://i.imgur.com/mUWQbva.jpg',
		'https://i.imgur.com/pL8XCjR.jpg',
		'https://i.imgur.com/SvkdbXo.jpg',
		'https://i.imgur.com/0FCCb6P.jpg',
		'https://i.imgur.com/9Iwg5jR.jpg',
		'https://i.imgur.com/GfTjQxe.jpg',
		'https://i.imgur.com/y1YXV6O.jpg',
		'https://i.imgur.com/JN4Kcqq.jpg',
		'https://i.imgur.com/mrkM8cC.jpg',
		'https://i.imgur.com/qcB6xv9.jpg',
		'https://i.imgur.com/NNTiSJl.jpg',
		'https://i.imgur.com/gEVJHHq.jpg',
		'https://i.imgur.com/JciATFN.jpg',
		'https://i.imgur.com/2CR4xAH.png',
		'https://i.imgur.com/Qgs9pZz.png',
		'https://i.imgur.com/dIthar9.jpg',
		'https://i.imgur.com/cFLEdsJ.jpg',
		'https://i.imgur.com/xHIrDyg.jpg',
		'https://i.imgur.com/VioakJu.jpg',
		'https://i.imgur.com/gRMzfsR.jpg',
		'https://i.imgur.com/EcpKRlB.jpg',
		'https://i.imgur.com/HAs10Hf.jpg',
		'https://i.imgur.com/9bl7L4r.jpg',
		'https://i.imgur.com/QuD3DrH.jpg',
		'https://i.imgur.com/7Hy9yYr.jpg',
		'https://i.imgur.com/pc6n8Df.jpg',
		'https://i.imgur.com/vBAZoMV.jpg',
		'https://i.imgur.com/oVD8elx.jpg',
		'https://i.imgur.com/s1PESuV.jpg',
		'https://i.imgur.com/Wcas0TS.jpg',
		'https://i.imgur.com/5DNwk6T.jpg',
		'https://i.imgur.com/6L9NHYC.jpg',
		'https://i.imgur.com/J4e6ko5.jpg',
		'https://i.imgur.com/JYL25Nh.jpg',
		'https://i.imgur.com/xEzA2ob.jpg',
		'https://i.imgur.com/kJEInrW.jpg',
		'https://i.imgur.com/3WYWBYa.jpg',
		'https://i.imgur.com/jE32Z2b.jpg',
		'https://i.imgur.com/3KXpZki.jpg',
		'https://i.imgur.com/MSi8LkF.png',
		'https://i.imgur.com/vBqtN80.jpg',
		'https://i.imgur.com/FVGL5e0.jpg',
		'https://i.imgur.com/w2mxApj.jpg',
		'https://i.imgur.com/d5OUv0R.jpg',
		'https://i.imgur.com/WKbuOiv.jpg',
		'https://i.imgur.com/yIf2tXh.jpg',
		'https://i.imgur.com/WS7IGL4.jpg',
		'https://i.imgur.com/zr1THev.jpg',
		'https://i.imgur.com/ZuZAOcb.jpg',
		'https://i.imgur.com/Qb4e9Qh.jpg',
		'https://i.imgur.com/RRloHqL.jpg',
		'https://i.imgur.com/VPcVBGU.jpg',
		'https://i.imgur.com/pqNbMhN.jpg',
		'https://i.imgur.com/Viqk4fa.jpg',
		'https://i.imgur.com/tYMVNDB.jpg',
		'https://i.imgur.com/APnSKEZ.jpg',
		'https://i.imgur.com/mCpw4rb.jpg',
		'https://i.imgur.com/HBrsx6Y.jpg',
		'https://i.imgur.com/XJV2eaf.jpg',
		'https://i.imgur.com/GPwbTuI.jpg',
		'https://i.imgur.com/9c4DxPG.jpg',
		'https://i.imgur.com/WTFD4z8.jpg',
		'https://i.imgur.com/CNVNNEa.jpg',
		'https://i.imgur.com/XEc7GqD.jpg',
		'https://i.imgur.com/Fp6me18.jpg',
		'https://i.imgur.com/iUXxGDd.jpg',
		'https://i.imgur.com/ldUnVgw.jpg',
		'https://i.imgur.com/vReUy3D.jpg',
		'https://i.imgur.com/5LAx4gB.gif',
		'https://i.imgur.com/SP8gduD.jpg',
		'https://i.imgur.com/09TGwAQ.jpg',
		'https://i.imgur.com/LVUYfDk.jpg',
		'https://i.imgur.com/hVj2WGa.gif',
		'https://i.imgur.com/pOq4nAq.gif',
		'https://i.imgur.com/2HY1oGI.jpg',
		'https://i.imgur.com/9IQc8UP.gif',
		'https://i.imgur.com/9FzhUCi.jpg',
		'https://i.imgur.com/tZXODr6.jpg',
		'https://i.imgur.com/4qa2u69.jpg',
		'https://i.imgur.com/7z67oJn.jpg',
		'https://i.imgur.com/0iz6RTk.jpg',
		'https://i.imgur.com/OvvIf3U.jpg',
		'https://i.imgur.com/81goiVd.jpg',
		'https://i.imgur.com/BIgVGhB.jpg',
		'https://i.imgur.com/i3yQxYv.jpg',
		'https://i.imgur.com/OCg7ECK.jpg',
		'https://i.imgur.com/DSnIpDB.jpg',
		'https://i.imgur.com/g7EpdUM.jpg',
		'https://i.imgur.com/RMMDKDm.jpg',
		'https://i.imgur.com/GjmM9UB.jpg',
		'https://i.imgur.com/O1jRmQd.jpg',
		'https://i.imgur.com/BjWu4fO.jpg',
		'https://i.imgur.com/nqg88iI.jpg',
		'https://i.imgur.com/Os7rgB4.jpg',
		'https://i.imgur.com/ZhcQlUr.jpg',
		'https://i.imgur.com/YPaCn7M.jpg',
		'https://i.imgur.com/JSFMNWi.jpg',
		'https://i.imgur.com/q1J0A61.jpg',
		'http://i.imgur.com/4DE9G6fh.gif',
		'https://i.imgur.com/EZ5NvZ1.gif',
		'https://i.imgur.com/DULd3u0.jpg',
		'https://i.imgur.com/b95psYp.jpg',
		'https://i.imgur.com/1x8woUe.jpg',
		'https://i.imgur.com/ueeH94Z.jpg',
		'https://i.imgur.com/6XmrTNk.jpg',
		'https://i.imgur.com/myHUp0H.jpg',
		'https://i.imgur.com/Zv2W9xt.jpg',
		'https://i.imgur.com/OxSJODH.jpg',
		'https://i.imgur.com/jcuIsoA.jpg',
		'https://i.imgur.com/MzRJqLH.jpg',
		'https://i.imgur.com/WskpbRZ.jpg'
	],
	Booty: [
		'http://media.obutts.ru/butts_preview/05442.jpg',
		'http://media.obutts.ru/butts_preview/05441.jpg',
		'http://media.obutts.ru/butts_preview/05440.jpg',
		'http://media.obutts.ru/butts_preview/05439.jpg',
		'http://media.obutts.ru/butts_preview/05438.jpg',
		'http://media.obutts.ru/butts_preview/05437.jpg',
		'http://media.obutts.ru/butts_preview/05436.jpg',
		'http://media.obutts.ru/butts_preview/05435.jpg',
		'http://media.obutts.ru/butts_preview/05434.jpg',
		'http://media.obutts.ru/butts_preview/05433.jpg',
		'http://media.obutts.ru/butts_preview/05432.jpg',
		'http://media.obutts.ru/butts_preview/05431.jpg',
		'http://media.obutts.ru/butts_preview/05430.jpg',
		'http://media.obutts.ru/butts_preview/05429.jpg',
		'http://media.obutts.ru/butts_preview/05428.jpg',
		'http://media.obutts.ru/butts_preview/05427.jpg',
		'http://media.obutts.ru/butts_preview/05426.jpg',
		'http://media.obutts.ru/butts_preview/05425.png',
		'http://media.obutts.ru/butts_preview/05424.jpg',
		'http://media.obutts.ru/butts_preview/05423.jpg',
		'http://media.obutts.ru/butts_preview/05422.jpg',
		'http://media.obutts.ru/butts_preview/05421.jpg',
		'http://media.obutts.ru/butts_preview/05420.jpg',
		'http://media.obutts.ru/butts_preview/05419.jpg',
		'http://media.obutts.ru/butts_preview/05418.jpg',
		'http://media.obutts.ru/butts_preview/05417.jpg',
		'http://media.obutts.ru/butts_preview/05416.jpg',
		'http://media.obutts.ru/butts_preview/05415.jpg',
		'http://media.obutts.ru/butts_preview/05414.jpg',
		'http://media.obutts.ru/butts_preview/05413.jpg',
		'http://media.obutts.ru/butts_preview/05412.jpg',
		'http://media.obutts.ru/butts_preview/05411.jpg',
		'http://media.obutts.ru/butts_preview/05410.jpg',
		'http://media.obutts.ru/butts_preview/05409.jpg',
		'http://media.obutts.ru/butts_preview/05408.jpg',
		'http://media.obutts.ru/butts_preview/05407.jpg',
		'http://media.obutts.ru/butts_preview/05406.png',
		'http://media.obutts.ru/butts_preview/05405.jpg',
		'http://media.obutts.ru/butts_preview/05404.jpg',
		'http://media.obutts.ru/butts_preview/05403.jpg',
		'http://media.obutts.ru/butts_preview/05402.jpg',
		'http://media.obutts.ru/butts_preview/05401.jpg',
		'http://media.obutts.ru/butts_preview/05400.jpg',
		'http://media.obutts.ru/butts_preview/05399.jpg',
		'http://media.obutts.ru/butts_preview/05398.jpg',
		'http://media.obutts.ru/butts_preview/05397.jpg',
		'http://media.obutts.ru/butts_preview/05396.jpg',
		'http://media.obutts.ru/butts_preview/05395.jpg',
		'http://media.obutts.ru/butts_preview/05394.jpg',
		'http://media.obutts.ru/butts_preview/05393.jpg',
		'http://media.obutts.ru/butts_preview/05392.jpg',
		'http://media.obutts.ru/butts_preview/05391.jpg',
		'http://media.obutts.ru/butts_preview/05390.jpg',
		'http://media.obutts.ru/butts_preview/05389.png',
		'http://media.obutts.ru/butts_preview/05388.jpg',
		'http://media.obutts.ru/butts_preview/05387.jpg',
		'http://media.obutts.ru/butts_preview/05386.jpg',
		'http://media.obutts.ru/butts_preview/05385.jpg',
		'http://media.obutts.ru/butts_preview/05384.jpg',
		'http://media.obutts.ru/butts_preview/05383.jpg',
		'http://media.obutts.ru/butts_preview/05382.jpg',
		'http://media.obutts.ru/butts_preview/05381.jpg',
		'http://media.obutts.ru/butts_preview/05380.jpg',
		'http://media.obutts.ru/butts_preview/05379.jpg',
		'http://media.obutts.ru/butts_preview/05378.jpg',
		'http://media.obutts.ru/butts_preview/05377.jpg',
		'http://media.obutts.ru/butts_preview/05376.jpg',
		'http://media.obutts.ru/butts_preview/05375.jpg',
		'http://media.obutts.ru/butts_preview/05374.jpg',
		'http://media.obutts.ru/butts_preview/05373.jpg',
		'http://media.obutts.ru/butts_preview/05372.jpg',
		'http://media.obutts.ru/butts_preview/05371.jpg',
		'http://media.obutts.ru/butts_preview/05370.jpg',
		'http://media.obutts.ru/butts_preview/05369.jpg',
		'http://media.obutts.ru/butts_preview/05368.jpg',
		'http://media.obutts.ru/butts_preview/05367.jpg',
		'http://media.obutts.ru/butts_preview/05366.jpg',
		'http://media.obutts.ru/butts_preview/05365.jpg',
		'http://media.obutts.ru/butts_preview/05364.jpg',
		'http://media.obutts.ru/butts_preview/05363.jpg',
		'http://media.obutts.ru/butts_preview/05362.jpg',
		'http://media.obutts.ru/butts_preview/05361.jpg',
		'http://media.obutts.ru/butts_preview/05360.jpg',
		'http://media.obutts.ru/butts_preview/05359.jpg',
		'http://media.obutts.ru/butts_preview/05358.jpg',
		'http://media.obutts.ru/butts_preview/05357.jpg',
		'http://media.obutts.ru/butts_preview/05356.png',
		'http://media.obutts.ru/butts_preview/05355.jpg',
		'http://media.obutts.ru/butts_preview/05354.jpg',
		'http://media.obutts.ru/butts_preview/05353.jpg',
		'http://media.obutts.ru/butts_preview/05352.jpg',
		'http://media.obutts.ru/butts_preview/05351.jpg',
		'http://media.obutts.ru/butts_preview/05350.jpg',
		'http://media.obutts.ru/butts_preview/05349.jpg',
		'http://media.obutts.ru/butts_preview/05348.jpg',
		'http://media.obutts.ru/butts_preview/05347.jpg',
		'http://media.obutts.ru/butts_preview/05346.png',
		'http://media.obutts.ru/butts_preview/05345.jpg',
		'http://media.obutts.ru/butts_preview/05344.jpg',
		'http://media.obutts.ru/butts_preview/05343.jpg',
		'https://i.imgur.com/a2Ac0C0.jpg',
		'https://i.imgur.com/jWopMTY.gif',
		'https://i.imgur.com/pMdMgub.jpg',
		'https://i.imgur.com/AjTnNKw.jpg',
		'https://i.imgur.com/MkTUkaQ.jpg',
		'https://i.imgur.com/Nbx6qNi.jpg',
		'https://i.imgur.com/nONtDJJ.jpg',
		'https://i.imgur.com/0eWdje6.jpg',
		'https://i.imgur.com/tBRJU42.jpg',
		'https://i.imgur.com/1Xjocbv.jpg',
		'https://i.imgur.com/rYHzWyX.jpg',
		'https://i.imgur.com/pQzPxqo.jpg',
		'https://i.imgur.com/tuKzBfH.jpg',
		'https://i.imgur.com/CPSyQgy.jpg',
		'https://i.imgur.com/K5f8zMY.jpg',
		'https://i.imgur.com/UJdN6MF.jpg',
		'https://i.imgur.com/fGj1Nzg.jpg',
		'https://i.imgur.com/mRRKR8Q.jpg',
		'https://i.imgur.com/43y1zNQ.png',
		'https://i.imgur.com/LB9Ots3.jpg',
		'https://i.imgur.com/NEs7xkq.jpg',
		'https://i.imgur.com/H2LMSzu.jpg',
		'https://i.imgur.com/0O1ii1C.jpg',
		'https://i.imgur.com/VvBNl3G.jpg',
		'https://i.imgur.com/u0RE2cl.jpg',
		'https://i.imgur.com/SpopDC9.jpg',
		'https://i.imgur.com/0rTIKex.png',
		'https://i.imgur.com/z1weNCy.jpg',
		'https://i.imgur.com/1hdGNIC.jpg',
		'https://i.imgur.com/IX0qrYj.jpg',
		'https://i.imgur.com/QO8F0Bg.jpg',
		'https://i.imgur.com/GRLzxXU.jpg',
		'https://i.imgur.com/XJQbnkY.jpg',
		'https://i.imgur.com/An1kIxn.jpg',
		'https://i.imgur.com/JsmTxmt.jpg',
		'https://i.imgur.com/J5IXVEU.jpg',
		'https://i.imgur.com/AuIbkUq.jpg',
		'https://i.imgur.com/DKHKlze.jpg',
		'https://i.imgur.com/YUPZR58.jpg',
		'https://i.imgur.com/X7oHZXe.jpg',
		'https://i.imgur.com/YPsdKvm.jpg',
		'https://i.imgur.com/N4GETLG.jpg',
		'https://i.imgur.com/qhwSeRH.jpg',
		'https://i.imgur.com/Ohafakp.jpg',
		'https://i.imgur.com/0pa0Uj0.jpg',
		'https://i.imgur.com/RkDzbRP.jpg',
		'https://i.imgur.com/Q28NZkM.jpg',
		'https://i.imgur.com/39M6PDC.jpg',
		'https://i.imgur.com/kyILxjp.jpg',
		'https://imgur.com/a/W7PVa',
		'https://i.imgur.com/1kCOhhq.jpg',
		'https://i.imgur.com/BkUQ2am.jpg',
		'https://i.imgur.com/iSPgYNF.jpg',
		'https://i.imgur.com/dBi4jbJ.jpg',
		'https://i.imgur.com/abvrmCM.jpg',
		'https://i.imgur.com/QLIzof2.jpg',
		'https://i.imgur.com/bNVRTYv.jpg',
		'https://i.imgur.com/aXpJhLB.jpg',
		'https://i.imgur.com/UbOSaXj.jpg',
		'https://i.imgur.com/7cfTNVA.png',
		'https://i.imgur.com/ykluu9v.jpg',
		'https://i.imgur.com/4fWoGbQ.jpg',
		'https://i.imgur.com/QzYu38Q.jpg',
		'https://i.imgur.com/kll21Dg.png',
		'https://i.imgur.com/KyN86tT.jpg',
		'https://i.imgur.com/3Z48uzr.jpg',
		'https://i.imgur.com/CDl7YdH.jpg',
		'https://i.imgur.com/Uz2w7w4.jpg',
		'https://i.imgur.com/9L5aVMu.jpg',
		'https://i.imgur.com/4KHCuCC.jpg',
		'https://i.imgur.com/YhItm3P.jpg',
		'https://i.imgur.com/qATofLI.jpg',
		'https://i.imgur.com/7gpbS94.jpg',
		'https://i.imgur.com/O1XlYZX.gif',
		'https://i.imgur.com/sufrM3Y.jpg',
		'https://i.imgur.com/cv1WBMU.jpg',
		'https://i.imgur.com/HlY93j2.jpg',
		'https://i.imgur.com/00xkjg0.png',
		'https://i.imgur.com/GUklwku.jpg',
		'https://i.imgur.com/z4KabXs.jpg',
		'https://i.imgur.com/6CEgOdC.jpg',
		'https://i.imgur.com/yMe2MOR.jpg',
		'https://i.imgur.com/RXe9bxK.jpg',
		'https://i.imgur.com/E8JzH8a.jpg',
		'https://i.imgur.com/PZkjHdB.jpg',
		'https://i.imgur.com/xEvkOSb.jpg',
		'https://i.imgur.com/7kt2N1J.jpg',
		'https://i.imgur.com/8tCYuHQ.jpg',
		'https://i.imgur.com/BB5MWa5.jpg',
		'https://i.imgur.com/dytCwZK.png',
		'https://i.imgur.com/UON2zU2.jpg',
		'https://i.imgur.com/OSam8Xy.jpg',
		'https://i.imgur.com/AjmdIps.gif',
		'https://i.imgur.com/Z8JfrBU.jpg',
		'https://i.imgur.com/xnyZfzP.jpg',
		'https://i.imgur.com/ZDWxipb.gif',
		'https://i.imgur.com/bcLoZqa.jpg',
		'https://i.imgur.com/0JU0kvR.jpg',
		'https://i.imgur.com/SvyrHOA.jpg',
		'https://i.imgur.com/7CKeNIo.jpg',
		'https://i.imgur.com/IbRXUzs.jpg',
		'https://i.imgur.com/2G2fuKa.jpg',
		'https://i.imgur.com/VcHeoOa.jpg',
		'https://i.imgur.com/QqFa2Qd.gif',
		'https://i.imgur.com/92fW9LO.jpg',
		'https://i.imgur.com/hxJMOe2.jpg',
		'https://i.imgur.com/e6sFLQa.jpg',
		'https://imgur.com/a/I2vul',
		'https://i.imgur.com/t34tEsQ.jpg',
		'https://i.imgur.com/um8VDTA.png',
		'https://i.imgur.com/dThdlO7.jpg',
		'https://i.imgur.com/J2gYziw.jpg',
		'https://i.imgur.com/ULeat2C.jpg',
		'https://imgur.com/a/aFRa8',
		'https://i.imgur.com/lscQpGA.jpg',
		'https://i.imgur.com/8CLPkP4.jpg',
		'https://imgur.com/a/TtWwh',
		'https://i.imgur.com/XXVGij6.jpg',
		'https://i.imgur.com/UDGD0Je.jpg',
		'https://i.imgur.com/3r6jny8.jpg',
		'https://i.imgur.com/GtENLWv.jpg',
		'https://i.imgur.com/ijypDT7.jpg',
		'https://imgur.com/a/pkj4g',
		'https://i.imgur.com/XbnwdqV.jpg',
		'https://imgur.com/a/nGFpn',
		'https://i.imgur.com/qJmuniC.jpg',
		'https://imgur.com/a/ADbpQ',
		'https://i.imgur.com/wSOsZJJ.jpg',
		'https://imgur.com/a/OPMat',
		'http://i.imgur.com/xJe6dxlh.gif',
		'https://i.imgur.com/DfjBtGk.jpg',
		'https://i.imgur.com/JUbcugv.png',
		'https://i.imgur.com/hIh9hv3.jpg',
		'https://i.imgur.com/iJyhBIY.jpg',
		'https://i.imgur.com/EHQMXVi.jpg',
		'https://i.imgur.com/8sTebmZ.jpg',
		'https://i.imgur.com/004eutp.jpg',
		'https://i.imgur.com/6Ot0IgL.jpg',
		'https://imgur.com/a/RLwe5',
		'https://imgur.com/a/LcSe5',
		'https://i.imgur.com/uhba8Dr.jpg',
		'https://i.imgur.com/KuWMJgh.jpg',
		'https://i.imgur.com/iYZklJI.jpg',
		'https://i.imgur.com/1FV3gRU.gif',
		'https://i.imgur.com/1KjtjdV.jpg',
		'https://i.imgur.com/pqAt0D1.jpg',
		'https://imgur.com/a/BfgBg',
		'https://i.imgur.com/jT9Z1hT.jpg',
		'https://imgur.com/a/U9k8t',
		'https://i.imgur.com/2OMjUiZ.jpg',
		'https://i.imgur.com/OtnyXqD.jpg',
		'https://i.imgur.com/adQD1LR.jpg',
		'https://i.imgur.com/pYoy4LO.jpg',
		'https://i.imgur.com/uF34RHg.jpg',
		'https://i.imgur.com/lU5BUOZ.jpg',
		'https://i.imgur.com/gkBnnkc.png',
		'https://i.imgur.com/uPd7viF.jpg',
		'https://i.imgur.com/9BnD4AY.jpg',
		'https://i.imgur.com/lIkmo2q.jpg',
		'https://i.imgur.com/R5QWu.jpg',
		'https://i.imgur.com/KxIYCpF.jpg',
		'https://i.imgur.com/jvqZqBf.png',
		'https://i.imgur.com/6H3e4cg.jpg',
		'https://i.imgur.com/Yn0M7HU.png',
		'https://i.imgur.com/LGg0p5q.jpg',
		'https://i.imgur.com/sW1cIQ3.jpg',
		'https://i.imgur.com/wJ6nU2S.jpg',
		'https://i.imgur.com/zHpx5Nz.png',
		'https://i.imgur.com/4hnINPl.jpg',
		'https://i.imgur.com/xPZaoZ4.jpg',
		'https://i.imgur.com/14sWvgh.jpg',
		'https://i.imgur.com/ZgRisII.jpg',
		'https://i.imgur.com/YE6HC8s.jpg',
		'https://i.imgur.com/cWHrPj2.jpg',
		'https://i.imgur.com/LSLsw1l.jpg',
		'https://i.imgur.com/fLbPmU7.jpg',
		'https://i.imgur.com/UTUggjt.jpg',
		'https://imgur.com/a/sIzR2',
		'https://i.imgur.com/hlBus8v.jpg',
		'https://i.imgur.com/A8F9K5K.jpg',
		'https://imgur.com/a/GiH4x',
		'https://i.imgur.com/lXzl1ua.jpg',
		'https://i.imgur.com/xGcluEZ.jpg',
		'https://i.imgur.com/Vlmnsdn.jpg',
		'https://i.imgur.com/Iget94K.jpg',
		'https://i.imgur.com/XTbZNLM.jpg',
		'https://i.imgur.com/kgPmnV9.jpg',
		'https://i.imgur.com/k2IPckO.jpg',
		'https://i.imgur.com/VUToZDA.jpg',
		'https://i.imgur.com/GccyTQe.jpg',
		'https://i.imgur.com/mbDW2Wf.jpg',
		'https://i.imgur.com/sKefTGq.jpg',
		'https://i.imgur.com/I4xJpM2.png',
		'https://i.imgur.com/7bjipd1.jpg',
		'https://i.imgur.com/in3Zm7c.jpg',
		'https://i.imgur.com/Ryb3Sl5.jpg',
		'https://i.imgur.com/C0KyUHc.jpg',
		'https://i.imgur.com/lIHowpQ.jpg',
		'https://imgur.com/a/1xO2F',
		'https://i.imgur.com/eeo1SlE.jpg',
		'https://i.imgur.com/LNNTpbA.jpg',
		'https://i.imgur.com/4vPEAOS.jpg',
		'https://i.imgur.com/sj8B6W8.jpg',
		'https://i.imgur.com/olRjAGR.jpg',
		'https://i.imgur.com/Xz1Fz9B.jpg',
		'https://i.imgur.com/45QWDJo.jpg',
		'https://i.imgur.com/4crS9sY.jpg',
		'https://i.imgur.com/jPMWYvR.jpg',
		'https://i.imgur.com/QDNGnK2.jpg',
		'https://i.imgur.com/JyQ5DQb.jpg',
		'https://i.imgur.com/aDFBJYe.jpg',
		'https://i.imgur.com/oF7rurj.jpg',
		'https://i.imgur.com/gxtnhJ3.jpg',
		'https://i.imgur.com/J0Hjphe.png',
		'https://i.imgur.com/t2FEQuG.jpg',
		'https://i.imgur.com/StOmF3u.png',
		'https://i.imgur.com/9vnchp5.jpg',
		'https://i.imgur.com/4LX09Ir.jpg',
		'https://i.imgur.com/E4xenT8.jpg',
		'https://i.imgur.com/LUUbTeT.png',
		'https://i.imgur.com/kIG3h0z.jpg',
		'https://i.imgur.com/GXU0EH7.jpg',
		'https://i.imgur.com/BBuFd5b.jpg',
		'https://i.imgur.com/zvCRgQ0.jpg',
		'https://i.imgur.com/XRY6q7C.png',
		'https://i.imgur.com/mEi0DZR.jpg',
		'https://i.imgur.com/O2cS1Z9.jpg',
		'https://i.imgur.com/g1K1BVM.jpg',
		'https://i.imgur.com/vhtdj4f.jpg',
		'https://i.imgur.com/gkzhFPB.jpg',
		'https://i.imgur.com/birmJOU.jpg',
		'https://i.imgur.com/diOmYQo.jpg',
		'https://i.imgur.com/5iFkBRx.mp4',
		'https://i.imgur.com/4sbAWWD.jpg',
		'https://i.imgur.com/kjrdh8i.jpg',
		'https://i.imgur.com/KtxunAO.jpg',
		'https://i.imgur.com/45gSkG2.jpg',
		'https://i.imgur.com/qa7Ax3d.jpg',
		'https://i.imgur.com/9vn1P06.jpg',
		'https://i.imgur.com/MBVqch9.jpg',
		'https://i.imgur.com/5gpfQWO.jpg',
		'https://i.imgur.com/AWPb80I.jpg',
		'https://i.imgur.com/wxEJ1Oe.jpg',
		'https://i.imgur.com/B2CwJth.jpg',
		'https://i.imgur.com/AyGNS6C.jpg',
		'https://i.imgur.com/jdco6HT.jpg',
		'https://i.imgur.com/tzwxvlY.jpg',
		'https://i.imgur.com/154pqmJ.jpg',
		'https://i.imgur.com/YdkljOn.jpg',
		'https://i.imgur.com/Pa2j2Gx.jpg',
		'https://i.imgur.com/GWIHFQm.jpg',
		'https://i.imgur.com/CsSHUaj.jpg',
		'https://i.imgur.com/rjrY0xf.png',
		'https://i.imgur.com/4ZklX1q.jpg',
		'https://i.imgur.com/2kdFsyD.png',
		'https://i.imgur.com/dqasJal.jpg',
		'https://i.imgur.com/NH52ggV.jpg',
		'https://i.imgur.com/HxCDYsj.jpg',
		'https://i.imgur.com/9PnBqbq.jpg',
		'https://i.imgur.com/1kVIbkM.jpg',
		'https://i.imgur.com/4uLEOqH.jpg',
		'https://i.imgur.com/s16VcA7.jpg',
		'https://i.imgur.com/ksSr456.png',
		'https://i.imgur.com/WRfhqYW.jpg',
		'https://i.imgur.com/pU93Z81.jpg',
		'https://i.imgur.com/EcoTHRh.jpg',
		'https://i.imgur.com/OlWYx0k.png',
		'https://i.imgur.com/PZoqXDS.jpg',
		'https://i.imgur.com/m97DXzn.jpg',
		'https://i.imgur.com/QuSIddH.jpg',
		'https://i.imgur.com/WI4Rr0U.jpg',
		'https://i.imgur.com/gaJkw2w.jpg',
		'https://i.imgur.com/Iu4sxaH.jpg',
		'https://i.imgur.com/2MU21KZ.jpg',
		'https://i.imgur.com/zx7IL4p.jpg',
		'https://i.imgur.com/AOCwrJl.png',
		'https://i.imgur.com/6Gsd1Qq.jpg',
		'https://i.imgur.com/OeuQssy.jpg',
		'https://i.imgur.com/h9C567M.jpg',
		'https://i.imgur.com/HhXEUrQ.jpg',
		'https://i.imgur.com/fq1T87K.jpg',
		'https://i.imgur.com/dRdPskI.jpg',
		'https://i.imgur.com/tCiPnOp.jpg',
		'https://i.imgur.com/sr1ZpYT.jpg',
		'https://i.imgur.com/hewa39O.jpg',
		'https://i.imgur.com/W1DKTZ5.jpg',
		'https://i.imgur.com/rvtbU2v.jpg',
		'https://i.imgur.com/kOMrREw.jpg',
		'https://i.imgur.com/qrMP4Jc.jpg',
		'https://i.imgur.com/aQdEWRr.jpg',
		'https://i.imgur.com/P5y8IEH.jpg',
		'https://i.imgur.com/yXfRtKH.jpg',
		'https://i.imgur.com/cktUttR.jpg',
		'https://i.imgur.com/VGMxwLs.gif',
		'https://i.imgur.com/kfKGpQB.mp4',
		'https://i.imgur.com/wTyvlbR.jpg',
		'https://i.imgur.com/OUFF85p.png',
		'https://i.imgur.com/7rIkWBL.jpg',
		'https://i.imgur.com/LUpIedP.jpg',
		'https://i.imgur.com/Q3rzbeU.jpg'
	],
	Pussy: [
		'https://i.imgur.com/WskpbRZ.jpg',
		'https://i.imgur.com/MzRJqLH.jpg',
		'https://i.imgur.com/KIsoD2s.jpg',
		'https://i.imgur.com/uDwJbZ8.jpg',
		'https://i.imgur.com/X6g3NY3.jpg',
		'https://i.imgur.com/ax0dAVS.jpg',
		'https://i.imgur.com/0IKFi3g.jpg',
		'https://i.imgur.com/z4NnPK7.jpg',
		'https://i.imgur.com/4TG6wKO.jpg',
		'https://i.imgur.com/DzH0mtQ.png',
		'https://i.imgur.com/XtRCIL5.jpg',
		'https://i.imgur.com/7MhWwBy.jpg',
		'https://i.imgur.com/ud7t1IB.jpg',
		'https://i.imgur.com/xKEmI2B.jpg',
		'https://i.imgur.com/BmlSliV.jpg',
		'https://i.imgur.com/n7Y7sRL.jpg',
		'https://i.imgur.com/367bwo6.jpg',
		'https://i.imgur.com/dPi8rHU.jpg',
		'https://i.imgur.com/pAhpIUr.jpg',
		'https://i.imgur.com/QsXy8wR.jpg',
		'https://i.imgur.com/o3JJwVI.jpg',
		'https://i.imgur.com/vfSs1lO.jpg',
		'https://imgur.com/a/V9H4I',
		'https://i.imgur.com/ZHPvGKP.jpg',
		'https://i.imgur.com/KYP1L3Q.jpg',
		'https://i.imgur.com/FaWhTU5.jpg',
		'https://i.imgur.com/14VOBvT.jpg',
		'https://i.imgur.com/JIJocoP.jpg',
		'https://i.imgur.com/ajcSXzX.jpg',
		'https://i.imgur.com/Zg4Cows.jpg',
		'https://i.imgur.com/l8CSeRf.jpg',
		'https://i.imgur.com/hjt8Icp.jpg',
		'https://i.imgur.com/AxAPSTw.jpg',
		'https://i.imgur.com/3YhjJO1.jpg',
		'https://i.imgur.com/1YLk8c2.jpg',
		'https://i.imgur.com/zOHFyMN.jpg',
		'https://i.imgur.com/mpWPHNh.jpg',
		'https://i.imgur.com/LEwGsmA.jpg',
		'https://i.imgur.com/K6TsXHW.jpg',
		'https://i.imgur.com/V1agdWW.jpg',
		'https://i.imgur.com/Ngkn8aq.jpg',
		'https://i.imgur.com/Bn7LVQm.png',
		'https://i.imgur.com/3AkCBKG.jpg',
		'https://i.imgur.com/Nm6fyTw.png',
		'https://i.imgur.com/I5flGrQ.gif',
		'https://imgur.com/a/IiANy',
		'https://i.imgur.com/2GEXTCn.jpg',
		'https://i.imgur.com/KEOPG9R.jpg',
		'https://i.imgur.com/Q36FvNV.jpg',
		'https://i.imgur.com/cNcMsXx.jpg',
		'https://imgur.com/a/59kjv',
		'https://i.imgur.com/04Q4ntl.png',
		'https://imgur.com/a/vllGM',
		'https://i.imgur.com/5gikyPK.jpg',
		'https://i.imgur.com/ln1lHhq.jpg',
		'https://i.imgur.com/NfukZJV.jpg',
		'https://i.imgur.com/9RK3vuG.gif',
		'https://i.imgur.com/lIvVIt2.jpg',
		'https://i.imgur.com/5zyIzGH.jpg',
		'https://i.imgur.com/XXDwxnt.jpg',
		'https://i.imgur.com/onJBXbh.jpg',
		'https://i.imgur.com/vK09oD7.jpg',
		'https://i.imgur.com/yQj6lMv.jpg',
		'https://i.imgur.com/zT98sT7.jpg',
		'https://i.imgur.com/eA4oWW8.jpg',
		'https://i.imgur.com/ZGg4Vzm.jpg',
		'https://i.imgur.com/YN1AxLU.jpg',
		'https://i.imgur.com/a9k5RqC.jpg',
		'https://i.imgur.com/rR9Eekc.jpg',
		'https://i.imgur.com/B27TYpJ.jpg',
		'https://i.imgur.com/RjeFmAh.jpg',
		'https://i.imgur.com/2ZoA46q.jpg',
		'https://i.imgur.com/LeLq75M.jpg',
		'https://i.imgur.com/g7x8oRn.jpg',
		'https://i.imgur.com/gZoet3s.jpg',
		'https://i.imgur.com/9K8p9eb.jpg',
		'https://i.imgur.com/IH3n2Bt.jpg',
		'https://i.imgur.com/VY2e0ly.jpg',
		'https://i.imgur.com/63dZwHe.jpg',
		'https://i.imgur.com/I47YyoN.jpg',
		'https://i.imgur.com/cXBostb.jpg',
		'https://i.imgur.com/L1k7ed4.jpg',
		'https://i.imgur.com/UQCrXa0.jpg',
		'https://i.imgur.com/7zHlzVM.jpg',
		'https://i.imgur.com/ZBO5DgP.jpg',
		'https://i.imgur.com/h2PYtvE.jpg',
		'https://i.imgur.com/3QRtXKf.jpg',
		'https://i.imgur.com/NGkvbgn.jpg',
		'https://i.imgur.com/Aiw1Bmi.jpg',
		'https://i.imgur.com/BjLWE31.jpg',
		'https://i.imgur.com/ZkN3EKe.jpg',
		'https://i.imgur.com/LZC3RQK.jpg',
		'https://i.imgur.com/NQS78Em.jpg',
		'https://i.imgur.com/1JEElRw.jpg',
		'https://i.imgur.com/c8jTx5Q.jpg',
		'https://i.imgur.com/z07vs3Y.jpg',
		'https://i.imgur.com/stxcW9N.jpg',
		'https://i.imgur.com/0AxsZwF.jpg',
		'https://i.imgur.com/BPKG0X5.jpg',
		'https://i.imgur.com/AjLYWc2.jpg',
		'https://i.imgur.com/xdwMBtQ.jpg',
		'https://i.imgur.com/Ugwxllh.jpg',
		'https://i.imgur.com/fAvhWjn.jpg',
		'https://i.imgur.com/T9WvktW.jpg',
		'https://i.imgur.com/itLnLt7.jpg',
		'https://i.imgur.com/9YzYmjj.jpg',
		'https://i.imgur.com/Z2DJewa.jpg',
		'https://i.imgur.com/5W3vdEz.png',
		'https://imgur.com/a/p6GEc',
		'https://i.imgur.com/VGqm5k9.jpg',
		'https://i.imgur.com/3f4NdLH.jpg',
		'https://i.imgur.com/ErGBWff.jpg',
		'https://i.imgur.com/RDkDih9.jpg',
		'https://i.imgur.com/eo9wPcS.jpg',
		'https://i.imgur.com/MabQ0Sh.jpg',
		'https://i.imgur.com/rvIrqFb.jpg',
		'https://i.imgur.com/b5GJYVo.gif',
		'https://i.imgur.com/Ae16Zlm.jpg',
		'https://i.imgur.com/jXWGEVs.jpg',
		'https://i.imgur.com/ekyNcyf.jpg',
		'https://i.imgur.com/QSjOuPh.gif',
		'https://i.imgur.com/I66UcTK.jpg',
		'https://i.imgur.com/Iv9jj.jpg',
		'https://i.imgur.com/5gumA.jpg',
		'https://i.imgur.com/M9Vrq.jpg',
		'https://i.imgur.com/M31Kc0i.jpg',
		'https://i.imgur.com/vf6A4B7.jpg',
		'https://i.imgur.com/MhtyfKS.jpg',
		'https://i.imgur.com/ELe8bJc.jpg',
		'https://i.imgur.com/9qu2OEk.jpg',
		'https://i.imgur.com/kBgEsnN.jpg',
		'https://i.imgur.com/psAGYoT.jpg',
		'https://i.imgur.com/Rc1DFVw.jpg',
		'https://i.imgur.com/IqT6K7Z.jpg',
		'https://i.imgur.com/U6niZdd.jpg',
		'https://i.imgur.com/DUZ4sM1.jpg',
		'https://i.imgur.com/nx67Xax.jpg',
		'https://i.imgur.com/PoyJaKz.jpg',
		'https://i.imgur.com/M1xAW0D.jpg',
		'https://i.imgur.com/xcp3ARX.jpg',
		'https://i.imgur.com/E2yQ347.jpg',
		'https://i.imgur.com/RgH7fLp.jpg',
		'https://i.imgur.com/u8jDBQ4.jpg',
		'https://i.imgur.com/9cPVLbS.jpg',
		'https://i.imgur.com/MLrEqAW.jpg',
		'https://i.imgur.com/Qku6k8p.jpg',
		'https://i.imgur.com/ACxLHEZ.jpg',
		'https://i.imgur.com/DEbgUGO.jpg',
		'https://i.imgur.com/VU6laRE.jpg',
		'https://i.imgur.com/n1C4FCP.jpg',
		'https://i.imgur.com/RYhunkT.jpg',
		'https://i.imgur.com/dOKXg43.jpg',
		'https://i.imgur.com/fhysx6I.jpg',
		'https://i.imgur.com/0fRxSu3.jpg',
		'https://i.imgur.com/lG0Hyy5.jpg',
		'https://i.imgur.com/ZQ6a85W.jpg',
		'https://i.imgur.com/4E1zdUE.jpg',
		'https://i.imgur.com/uokOTD2.jpg',
		'https://i.imgur.com/LtC7J3q.jpg',
		'https://i.imgur.com/yrOgJZK.jpg',
		'https://i.imgur.com/68AMmZp.jpg',
		'https://i.imgur.com/9PbDJiA.jpg',
		'https://i.imgur.com/GSmevwd.jpg',
		'https://i.imgur.com/f6LxlB0.jpg',
		'https://i.imgur.com/bgWn6LZ.jpg',
		'https://i.imgur.com/5UmQlYs.jpg',
		'https://i.imgur.com/nM4SuRA.jpg',
		'https://i.imgur.com/bnTdmsI.jpg',
		'https://i.imgur.com/WngIL4k.jpg',
		'https://i.imgur.com/5btu32V.gif',
		'https://i.imgur.com/LjkAqZC.jpg',
		'https://i.imgur.com/oYXwDaT.jpg',
		'https://i.imgur.com/NKMsfP3.jpg',
		'https://i.imgur.com/bKD32on.jpg',
		'https://i.imgur.com/qEubETe.jpg',
		'https://i.imgur.com/n7Xfbrb.jpg',
		'https://i.imgur.com/0RFN3VT.jpg',
		'https://i.imgur.com/BD52uUQ.jpg',
		'https://i.imgur.com/A7xaXzs.jpg',
		'https://i.imgur.com/VYLKxJn.jpg',
		'https://i.imgur.com/pPp7DNZ.jpg',
		'https://i.imgur.com/NIjPjQv.jpg',
		'https://i.imgur.com/psULMpO.jpg',
		'https://i.imgur.com/qv88rAM.jpg',
		'https://i.imgur.com/unsSpIv.jpg',
		'https://i.imgur.com/V3I2p6n.jpg',
		'https://i.imgur.com/2qAZerK.jpg',
		'https://i.imgur.com/ipC2n6i.jpg',
		'https://i.imgur.com/L5DGRuc.jpg',
		'https://i.imgur.com/NHWV4og.jpg',
		'https://i.imgur.com/w3ihRPW.jpg',
		'https://i.imgur.com/AxgUp9q.jpg',
		'https://i.imgur.com/dSB0ulG.jpg',
		'https://i.imgur.com/mmGM3Tb.jpg',
		'https://i.imgur.com/9TLGotO.jpg',
		'https://i.imgur.com/l6ba3Vd.jpg',
		'https://i.imgur.com/FEeb6MF.jpg',
		'https://i.imgur.com/DLjLXQI.jpg',
		'https://i.imgur.com/xojxJPH.jpg',
		'https://i.imgur.com/z9FNstV.jpg',
		'https://i.imgur.com/gtLV9V7.jpg',
		'https://i.imgur.com/o6TzuKq.jpg',
		'https://i.imgur.com/h8ujxZb.jpg',
		'https://i.imgur.com/1mnWiv3.jpg',
		'https://i.imgur.com/eIVSqkb.jpg',
		'https://i.imgur.com/4Kh07Z5.jpg',
		'https://i.imgur.com/1WzPMaz.jpg',
		'https://i.imgur.com/HRJmisO.jpg',
		'https://i.imgur.com/PhZV181.gif',
		'https://i.imgur.com/y5TtCGM.jpg',
		'https://i.imgur.com/ctDHEvA.jpg',
		'https://i.imgur.com/AckLVgl.jpg',
		'https://i.imgur.com/SgzUOwa.jpg',
		'https://i.imgur.com/pisVnNT.jpg',
		'https://i.imgur.com/Tjkc6y0.jpg',
		'https://i.imgur.com/6sY25o7.jpg',
		'https://i.imgur.com/qQiML9J.jpg',
		'https://i.imgur.com/8qYsqQz.jpg',
		'https://i.imgur.com/H3hAtwC.jpg',
		'https://i.imgur.com/So6IoXI.jpg',
		'https://i.imgur.com/oCmY4U0.jpg',
		'https://i.imgur.com/VVjc9az.jpg',
		'https://i.imgur.com/lvztksJ.jpg',
		'https://i.imgur.com/zw60Yty.jpg',
		'https://i.imgur.com/0MBOC3m.jpg'
	]
};

module.exports.Permissions = {
	ADMINISTRATOR: 'Administrator',
	VIEW_AUDIT_LOG: 'View Audit Log',
	MANAGE_GUILD: 'Manage Server',
	MANAGE_ROLES: 'Manage Roles',
	MANAGE_CHANNELS: 'Manage Channels',
	KICK_MEMBERS: 'Kick Members',
	BAN_MEMBERS: 'Ban Members',
	CREATE_INSTANT_INVITE: 'Create Instant Invite',
	CHANGE_NICKNAME: 'Change Nickname',
	MANAGE_NICKNAMES: 'Manage Nicknames',
	MANAGE_EMOJIS: 'Manage Emojis',
	MANAGE_WEBHOOKS: 'Manage Webhooks',
	VIEW_CHANNEL: 'Read Text Channels and See Voice Channels',
	SEND_MESSAGES: 'Send Messages',
	SEND_TTS_MESSAGES: 'Send TTS Messages',
	MANAGE_MESSAGES: 'Manage Messages',
	EMBED_LINKS: 'Embed Links',
	ATTACH_FILES: 'Attach Files',
	READ_MESSAGE_HISTORY: 'Read Message History',
	MENTION_EVERYONE: 'Mention Everyone',
	USE_EXTERNAL_EMOJIS: 'Use External Emojis',
	ADD_REACTIONS: 'Add Reactions',
	CONNECT: 'Connect',
	SPEAK: 'Speak',
	MUTE_MEMBERS: 'Mute Members',
	DEAFEN_MEMBERS: 'Deafen Members',
	MOVE_MEMBERS: 'Move Members',
	USE_VAD: 'Use Voice Activity'
};
